// GENERATED by scripts/export_cases.py from data-pipeline/stlab/cases/definitions.py. Do not edit.
//
// The Python registry is the single source for the case matrix. CI re-runs the generator and fails if
// this file would change, so the browser and the offline bake can never be running different
// experiments while both reporting the same case ids.
//
// Every field is the one ADR-0069 clause 4 requires of a case: its category, the scientific reason it
// is in the matrix, its expected behaviour, the kill criterion that says what result would mean the
// code is wrong, and its split assignment.

import type { ReclaimMethod, StackingMethod, StreamStructure } from './types';

export interface CaseDef {
  id: string;
  category: string;
  reason: string;
  expectedBand: string;
  killCriterion: string;
  realOrSynthetic: string;
  split: string;
  stacking: StackingMethod;
  reclaim: ReclaimMethod;
  nPasses: number;
  reclaimRate: number;
  cutTonnes: number;
  startFraction: number;
  sr: number;
  reposeDeg: number;
  reposeCoarseDeg: number;
  structure: StreamStructure;
  rangeT: number;
  nDumps: number;
  coarseSd: number;
  nx: number;
  ny: number;
  cellM: number;
  tags: string[];
}

export const CATEGORY_LABELS: Record<string, string> = {
  "stacking-geometry": "How the pile was built",
  "reclaim-method": "How the pile was taken back",
  "input-variability": "What the incoming stream looked like",
  "segregation-regime": "How strongly the material sorted itself",
  "control": "Controls with numerical kill criteria"
};

export const CASES: CaseDef[] = [
  {
    "id": "G01_chevron",
    "category": "stacking-geometry",
    "reason": "The reference longitudinal bed. Many thin gable layers on one centre line; also serves as the full-face reference of the reclaim axis, so that axis carries no duplicated row.",
    "expectedBand": "VRR clearly below cone shell and above chevcon; layers crossed per cut close to the pass count",
    "killCriterion": "If VRR(G01) is not below VRR(G03), the layer accounting or the reclaim geometry is wrong",
    "realOrSynthetic": "synthetic",
    "split": "holdout",
    "stacking": "chevron",
    "reclaim": "fullface",
    "nPasses": 24,
    "reclaimRate": 1.0,
    "cutTonnes": 900.0,
    "startFraction": 0.35,
    "sr": 1.0,
    "reposeDeg": 37.0,
    "reposeCoarseDeg": 37.0,
    "structure": "stationary",
    "rangeT": 4000.0,
    "nDumps": 320,
    "coarseSd": 0.08,
    "nx": 64,
    "ny": 24,
    "cellM": 3.0,
    "tags": [
      "reference",
      "fullface-reference"
    ]
  },
  {
    "id": "G02_windrow",
    "category": "stacking-geometry",
    "reason": "The same longitudinal travel with the deposition axis slewing across three cords, so the toe bias is spread over several crests instead of two flanks.",
    "expectedBand": "VRR near chevron; a smaller toe-minus-apex coarse delta than chevron at the same Sr",
    "killCriterion": "If the segregation index is not below chevron's, the lateral spreading is not reaching the ledger",
    "realOrSynthetic": "synthetic",
    "split": "holdout",
    "stacking": "windrow",
    "reclaim": "fullface",
    "nPasses": 24,
    "reclaimRate": 1.0,
    "cutTonnes": 900.0,
    "startFraction": 0.35,
    "sr": 1.0,
    "reposeDeg": 37.0,
    "reposeCoarseDeg": 37.0,
    "structure": "stationary",
    "rangeT": 4000.0,
    "nDumps": 320,
    "coarseSd": 0.08,
    "nx": 64,
    "ny": 24,
    "cellM": 3.0,
    "tags": []
  },
  {
    "id": "G03_coneshell",
    "category": "stacking-geometry",
    "reason": "Stepping cones, each shelling over the last. The method the literature reports as unsuitable when homogenization matters, and the published anchor at VRR 0.232.",
    "expectedBand": "VRR in the 0.2 to 0.35 band, consistent with the published cone shell floor",
    "killCriterion": "If VRR lands below 0.15 this method is blending far better than any published result, which means the cut is crossing layers the geometry should not expose",
    "realOrSynthetic": "synthetic",
    "split": "holdout",
    "stacking": "coneshell",
    "reclaim": "fullface",
    "nPasses": 24,
    "reclaimRate": 1.0,
    "cutTonnes": 900.0,
    "startFraction": 0.35,
    "sr": 1.0,
    "reposeDeg": 37.0,
    "reposeCoarseDeg": 37.0,
    "structure": "stationary",
    "rangeT": 4000.0,
    "nDumps": 320,
    "coarseSd": 0.08,
    "nx": 64,
    "ny": 24,
    "cellM": 3.0,
    "tags": [
      "anchored"
    ]
  },
  {
    "id": "G04_strata",
    "category": "stacking-geometry",
    "reason": "Inclined layers built against one flank. Intermediate blending, and the case that shows layer inclination is an operating variable in its own right.",
    "expectedBand": "VRR between chevron and cone shell",
    "killCriterion": "If VRR is outside the chevron-to-cone-shell interval, the lean is not producing inclined layers",
    "realOrSynthetic": "synthetic",
    "split": "holdout",
    "stacking": "strata",
    "reclaim": "fullface",
    "nPasses": 24,
    "reclaimRate": 1.0,
    "cutTonnes": 900.0,
    "startFraction": 0.35,
    "sr": 1.0,
    "reposeDeg": 37.0,
    "reposeCoarseDeg": 37.0,
    "structure": "stationary",
    "rangeT": 4000.0,
    "nDumps": 320,
    "coarseSd": 0.08,
    "nx": 64,
    "ny": 24,
    "cellM": 3.0,
    "tags": []
  },
  {
    "id": "G05_chevcon",
    "category": "stacking-geometry",
    "reason": "Chevron travel with the pattern advancing along the pile. The best-blending industrial method and the second published anchor, at VRR 0.121 with about a ten to one variance reduction reported for chevcon reclaimed full-face.",
    "expectedBand": "The lowest VRR of the five, at or below about 0.15",
    "killCriterion": "If VRR(G05) is not the lowest of the five geometries, the ordering the whole literature agrees on has not been reproduced and the engine is wrong",
    "realOrSynthetic": "synthetic",
    "split": "holdout",
    "stacking": "chevcon",
    "reclaim": "fullface",
    "nPasses": 24,
    "reclaimRate": 1.0,
    "cutTonnes": 900.0,
    "startFraction": 0.35,
    "sr": 1.0,
    "reposeDeg": 37.0,
    "reposeCoarseDeg": 37.0,
    "structure": "stationary",
    "rangeT": 4000.0,
    "nDumps": 320,
    "coarseSd": 0.08,
    "nx": 64,
    "ny": 24,
    "cellM": 3.0,
    "tags": [
      "anchored",
      "best"
    ]
  },
  {
    "id": "R02_bucketwheel",
    "category": "reclaim-method",
    "reason": "A slewing bucket wheel cutting a bench: a third of the width, upper half of each column. It crosses the exposed layers and misses the rest.",
    "expectedBand": "VRR above full-face and below end reclaim",
    "killCriterion": "If VRR(R02) is at or below VRR(G01) the bench is somehow crossing more layers than a full-face cut, which is geometrically impossible",
    "realOrSynthetic": "synthetic",
    "split": "holdout",
    "stacking": "chevron",
    "reclaim": "bucketwheel",
    "nPasses": 24,
    "reclaimRate": 1.0,
    "cutTonnes": 900.0,
    "startFraction": 0.35,
    "sr": 1.0,
    "reposeDeg": 37.0,
    "reposeCoarseDeg": 37.0,
    "structure": "stationary",
    "rangeT": 4000.0,
    "nDumps": 320,
    "coarseSd": 0.08,
    "nx": 64,
    "ny": 24,
    "cellM": 3.0,
    "tags": []
  },
  {
    "id": "R03_end",
    "category": "reclaim-method",
    "reason": "End reclaim working the exposed end face, which over-represents the most recently stacked material.",
    "expectedBand": "VRR well above full-face; the reclaimed stream visibly lags the input rather than averaging it",
    "killCriterion": "If VRR(R03) is below VRR(R02) the recency bias is not reaching the ledger",
    "realOrSynthetic": "synthetic",
    "split": "holdout",
    "stacking": "chevron",
    "reclaim": "end",
    "nPasses": 24,
    "reclaimRate": 1.0,
    "cutTonnes": 900.0,
    "startFraction": 0.35,
    "sr": 1.0,
    "reposeDeg": 37.0,
    "reposeCoarseDeg": 37.0,
    "structure": "stationary",
    "rangeT": 4000.0,
    "nDumps": 320,
    "coarseSd": 0.08,
    "nx": 64,
    "ny": 24,
    "cellM": 3.0,
    "tags": []
  },
  {
    "id": "R04_loader",
    "category": "reclaim-method",
    "reason": "Scattered front-end loader bites from the top of a few accessible columns. Fewest layers, least spatial averaging, and the real run-of-mine pad case rather than the blending-bed ideal.",
    "expectedBand": "The worst VRR of the reclaim axis, plausibly close to 1 (little or no blending)",
    "killCriterion": "If VRR(R04) is the best of the reclaim axis the cell selection is wrong",
    "realOrSynthetic": "synthetic",
    "split": "holdout",
    "stacking": "chevron",
    "reclaim": "loader",
    "nPasses": 24,
    "reclaimRate": 1.0,
    "cutTonnes": 900.0,
    "startFraction": 0.35,
    "sr": 1.0,
    "reposeDeg": 37.0,
    "reposeCoarseDeg": 37.0,
    "structure": "stationary",
    "rangeT": 4000.0,
    "nDumps": 320,
    "coarseSd": 0.08,
    "nx": 64,
    "ny": 24,
    "cellM": 3.0,
    "tags": []
  },
  {
    "id": "V01_short_range",
    "category": "input-variability",
    "reason": "Grade correlation range much shorter than the tonnage in one layer, so successive layers are nearly independent. This is the case where the independent-layer bound is nearly attainable.",
    "expectedBand": "Blending efficiency against the 1/N bound the highest of the four V cases",
    "killCriterion": "If the efficiency here is not the highest of V01 to V04, the variogram range is not reaching the simulation",
    "realOrSynthetic": "synthetic",
    "split": "holdout",
    "stacking": "chevron",
    "reclaim": "fullface",
    "nPasses": 24,
    "reclaimRate": 1.0,
    "cutTonnes": 900.0,
    "startFraction": 0.35,
    "sr": 1.0,
    "reposeDeg": 37.0,
    "reposeCoarseDeg": 37.0,
    "structure": "short_range",
    "rangeT": 4000.0,
    "nDumps": 320,
    "coarseSd": 0.08,
    "nx": 64,
    "ny": 24,
    "cellM": 3.0,
    "tags": []
  },
  {
    "id": "V02_long_range",
    "category": "input-variability",
    "reason": "Correlation range longer than the whole pile, so every layer carries nearly the same grade and the bed has almost nothing to average. Ships as a headline case rather than being buried, because it is the honest one.",
    "expectedBand": "VRR close to 1 and efficiency far below V01; the bed barely helps",
    "killCriterion": "If VRR here is comparable to V01 the input autocorrelation is being ignored somewhere",
    "realOrSynthetic": "synthetic",
    "split": "holdout",
    "stacking": "chevron",
    "reclaim": "fullface",
    "nPasses": 24,
    "reclaimRate": 1.0,
    "cutTonnes": 900.0,
    "startFraction": 0.35,
    "sr": 1.0,
    "reposeDeg": 37.0,
    "reposeCoarseDeg": 37.0,
    "structure": "long_range",
    "rangeT": 4000.0,
    "nDumps": 320,
    "coarseSd": 0.08,
    "nx": 64,
    "ny": 24,
    "cellM": 3.0,
    "tags": [
      "honest"
    ]
  },
  {
    "id": "V03_trending",
    "category": "input-variability",
    "reason": "A linear grade drift across the shift on top of the correlated field. The mean moves, so variance reduction on the whole record becomes a misleading summary of what the plant sees.",
    "expectedBand": "VRR may look acceptable while the reclaimed mean drifts; the drift must be visible on the stream plot",
    "killCriterion": "If the reclaimed mean does not drift with the input, the trend is not being generated",
    "realOrSynthetic": "synthetic",
    "split": "holdout",
    "stacking": "chevron",
    "reclaim": "fullface",
    "nPasses": 24,
    "reclaimRate": 1.0,
    "cutTonnes": 900.0,
    "startFraction": 0.35,
    "sr": 1.0,
    "reposeDeg": 37.0,
    "reposeCoarseDeg": 37.0,
    "structure": "trending",
    "rangeT": 4000.0,
    "nDumps": 320,
    "coarseSd": 0.08,
    "nx": 64,
    "ny": 24,
    "cellM": 3.0,
    "tags": [
      "honest"
    ]
  },
  {
    "id": "V04_bimodal",
    "category": "input-variability",
    "reason": "Two ore types arriving in runs, as they would from two dig faces. The reclaimed histogram stays bimodal even when the VRR looks respectable, which is why the distribution has to be shown and not only its second moment.",
    "expectedBand": "Reclaimed grade histogram visibly bimodal despite a VRR below 0.4",
    "killCriterion": "If the reclaimed histogram is unimodal the mixture is not surviving into the cuts and the generator is wrong",
    "realOrSynthetic": "synthetic",
    "split": "holdout",
    "stacking": "chevron",
    "reclaim": "fullface",
    "nPasses": 24,
    "reclaimRate": 1.0,
    "cutTonnes": 900.0,
    "startFraction": 0.35,
    "sr": 1.0,
    "reposeDeg": 37.0,
    "reposeCoarseDeg": 37.0,
    "structure": "bimodal",
    "rangeT": 4000.0,
    "nDumps": 320,
    "coarseSd": 0.08,
    "nx": 64,
    "ny": 24,
    "cellM": 3.0,
    "tags": [
      "honest"
    ]
  },
  {
    "id": "S01_strong_sieving",
    "category": "segregation-regime",
    "reason": "A wide size distribution with a high segregation number, so kinetic sieving drives coarse to the toe strongly enough to bias what each reclaim cut contains.",
    "expectedBand": "A large positive toe-minus-apex coarse-fraction delta; cut composition varying with the reclaim front position",
    "killCriterion": "If the segregation index is near zero at Sr = 4 the flowing-layer solver is not coupled to the ledger",
    "realOrSynthetic": "synthetic",
    "split": "holdout",
    "stacking": "chevron",
    "reclaim": "fullface",
    "nPasses": 24,
    "reclaimRate": 1.0,
    "cutTonnes": 900.0,
    "startFraction": 0.35,
    "sr": 4.0,
    "reposeDeg": 37.0,
    "reposeCoarseDeg": 37.0,
    "structure": "stationary",
    "rangeT": 4000.0,
    "nDumps": 320,
    "coarseSd": 0.16,
    "nx": 64,
    "ny": 24,
    "cellM": 3.0,
    "tags": [
      "segregation"
    ]
  },
  {
    "id": "S02_stratifying",
    "category": "segregation-regime",
    "reason": "The Makse regime: the coarse species has the larger angle of repose, which is the published condition under which a poured bidisperse mixture spontaneously stratifies into alternating layers rather than merely segregating.",
    "expectedBand": "Alternating coarse and fine bands visible in the cutaway; a larger segregation index than S01 at the same Sr is NOT expected, the signature is the layering, not the magnitude",
    "killCriterion": "If the cutaway shows no alternation at a five degree repose difference, the coarse repose angle is not being used",
    "realOrSynthetic": "synthetic",
    "split": "holdout",
    "stacking": "coneshell",
    "reclaim": "fullface",
    "nPasses": 24,
    "reclaimRate": 1.0,
    "cutTonnes": 900.0,
    "startFraction": 0.35,
    "sr": 2.0,
    "reposeDeg": 34.0,
    "reposeCoarseDeg": 39.0,
    "structure": "stationary",
    "rangeT": 4000.0,
    "nDumps": 320,
    "coarseSd": 0.16,
    "nx": 64,
    "ny": 24,
    "cellM": 3.0,
    "tags": [
      "segregation",
      "makse"
    ]
  },
  {
    "id": "C01_perfect_mixer",
    "category": "control",
    "reason": "The degenerate bound: a single-cell pad with no geometry at all, so a reclaim cut is a tonnage-weighted mean of everything in the pile. The achieved VRR must equal the independent-layer bound.",
    "expectedBand": "Achieved VRR equal to 1/N within the multi-seed band",
    "killCriterion": "If the achieved VRR differs from 1/N by more than the band, the VRR implementation is wrong and every number in the product is suspect",
    "realOrSynthetic": "synthetic",
    "split": "holdout",
    "stacking": "coneshell",
    "reclaim": "fullface",
    "nPasses": 1,
    "reclaimRate": 1.0,
    "cutTonnes": 2400.0,
    "startFraction": 0.35,
    "sr": 1.0,
    "reposeDeg": 37.0,
    "reposeCoarseDeg": 37.0,
    "structure": "short_range",
    "rangeT": 4000.0,
    "nDumps": 240,
    "coarseSd": 0.08,
    "nx": 1,
    "ny": 1,
    "cellM": 40.0,
    "tags": [
      "control"
    ]
  },
  {
    "id": "C02_no_segregation",
    "category": "control",
    "reason": "The negative control: the segregation number set to zero, which makes the Gray-Thornton equation degenerate to pure tracer advection. Any size sorting produced by the SOLVER is then leaking in from somewhere it should not.",
    "expectedBand": "Every lot in the pile still carries exactly the coarse fraction of the truck it came from. The aggregate toe-minus-apex delta is NOT expected to be zero: different dumps carry different size distributions and land in different places, so the geometry alone produces a small spatial pattern. Measured at Sr = 0 it is about -0.01, against about +0.44 at Sr = 1, so the solver contribution is two orders of magnitude larger than the geometric one.",
    "killCriterion": "A lot whose coarse fraction differs from its source dump's by more than 1e-12 at Sr = 0 means the solver is modifying the size split when it has been switched off",
    "realOrSynthetic": "synthetic",
    "split": "holdout",
    "stacking": "chevron",
    "reclaim": "fullface",
    "nPasses": 24,
    "reclaimRate": 1.0,
    "cutTonnes": 900.0,
    "startFraction": 0.35,
    "sr": 0.0,
    "reposeDeg": 37.0,
    "reposeCoarseDeg": 37.0,
    "structure": "stationary",
    "rangeT": 4000.0,
    "nDumps": 320,
    "coarseSd": 0.16,
    "nx": 64,
    "ny": 24,
    "cellM": 3.0,
    "tags": [
      "control"
    ]
  },
  {
    "id": "C03_starvation",
    "category": "control",
    "reason": "The boundary: reclaim runs at three times the stacking rate, so the pile is driven empty. A buffer model that has never been driven to its boundary has not been tested there.",
    "expectedBand": "The pile empties, the run reports starvation, and no tonnage is negative or NaN",
    "killCriterion": "A NaN, a negative tonnage, or a run that does not report starvation is a hard failure",
    "realOrSynthetic": "synthetic",
    "split": "holdout",
    "stacking": "chevron",
    "reclaim": "fullface",
    "nPasses": 24,
    "reclaimRate": 3.0,
    "cutTonnes": 900.0,
    "startFraction": 0.15,
    "sr": 1.0,
    "reposeDeg": 37.0,
    "reposeCoarseDeg": 37.0,
    "structure": "stationary",
    "rangeT": 4000.0,
    "nDumps": 320,
    "coarseSd": 0.08,
    "nx": 64,
    "ny": 24,
    "cellM": 3.0,
    "tags": [
      "control",
      "edge"
    ]
  }
];

export const CASES_BY_ID: Record<string, CaseDef> = Object.fromEntries(CASES.map((c) => [c.id, c]));

export function casesByCategory(): Array<{ category: string; label: string; cases: CaseDef[] }> {
  const order = Object.keys(CATEGORY_LABELS);
  return order.map((category) => ({
    category,
    label: CATEGORY_LABELS[category],
    cases: CASES.filter((c) => c.category === category),
  })).filter((g) => g.cases.length > 0);
}
