// GENERATED by scripts/export_cases.py from data-pipeline/stlab/cases/definitions.py. Do not edit.
//
// The Python registry is the single source for the case matrix. CI re-runs the generator and fails if
// this file would change, so the browser and the offline bake can never be running different
// experiments while both reporting the same case ids.
//
// Every field is the one ADR-0069 clause 4 requires of a case: its category, the scientific reason it
// is in the matrix, its expected behaviour, the kill criterion that says what result would mean the
// code is wrong, and its split assignment.

import type { ReclaimMethod, StackingMethod, StreamStructure } from './types';

/**
 * One named operating regime of a case: a parameter override plus what it exists to show.
 *
 * A variant is not a different case. It is the same experiment at a different point on the one knob
 * that decides its category's answer, so the case's reason, expected band and kill criterion all
 * still apply, which is why a variant carries a note rather than its own kill criterion.
 *
 * The overrides are applied to the LIVE lane, so selecting a regime recomputes the real engine in the
 * browser rather than loading a pre-baked picture of it.
 */
export interface VariantDef {
  id: string;
  labelEn: string;
  labelEs: string;
  noteEn: string;
  noteEs: string;
  overrides: Partial<Pick<CaseDef, 'nPasses' | 'cutTonnes' | 'rangeT' | 'sr'>>;
}

export interface CaseDef {
  id: string;
  category: string;
  reason: string;
  expectedBand: string;
  killCriterion: string;
  realOrSynthetic: string;
  split: string;
  stacking: StackingMethod;
  reclaim: ReclaimMethod;
  nPasses: number;
  reclaimRate: number;
  cutTonnes: number;
  startFraction: number;
  sr: number;
  reposeDeg: number;
  reposeCoarseDeg: number;
  structure: StreamStructure;
  rangeT: number;
  nDumps: number;
  coarseSd: number;
  nx: number;
  ny: number;
  cellM: number;
  tags: string[];
  /**
   * The case's operating regimes. EMPTY for a control, and that is deliberate: a control is one
   * point carrying a numerical kill criterion, and sweeping it would destroy the property that makes
   * it a control. Padding the list to reach a chip count would be fabricating regimes.
   */
  variants: VariantDef[];
}

export const CATEGORY_LABELS: Record<string, string> = {
  "stacking-geometry": "How the pile was built",
  "reclaim-method": "How the pile was taken back",
  "input-variability": "What the incoming stream looked like",
  "segregation-regime": "How strongly the material sorted itself",
  "control": "Controls with numerical kill criteria"
};

export const CASES: CaseDef[] = [
  {
    "id": "G01_chevron",
    "category": "stacking-geometry",
    "reason": "The reference longitudinal bed. Many thin gable layers on one centre line; also serves as the full-face reference of the reclaim axis, so that axis carries no duplicated row.",
    "expectedBand": "VRR clearly below cone shell and above chevcon; layers crossed per cut close to the pass count",
    "killCriterion": "If VRR(G01) is not below VRR(G03), the layer accounting or the reclaim geometry is wrong",
    "realOrSynthetic": "synthetic",
    "split": "holdout",
    "stacking": "chevron",
    "reclaim": "fullface",
    "nPasses": 24,
    "reclaimRate": 1.0,
    "cutTonnes": 900.0,
    "startFraction": 0.35,
    "sr": 1.0,
    "reposeDeg": 37.0,
    "reposeCoarseDeg": 37.0,
    "structure": "stationary",
    "rangeT": 4000.0,
    "nDumps": 320,
    "coarseSd": 0.08,
    "nx": 64,
    "ny": 24,
    "cellM": 3.0,
    "tags": [
      "reference",
      "fullface-reference"
    ],
    "variants": [
      {
        "id": "p6",
        "labelEn": "6 passes",
        "labelEs": "6 pasadas",
        "noteEn": "Too few layers to blend. The bed is a stockpile with a shape, and the ratio stays near one.",
        "noteEs": "Muy pocas capas para mezclar. La cama es un acopio con forma y la razón se queda cerca de uno.",
        "overrides": {
          "nPasses": 6
        }
      },
      {
        "id": "p12",
        "labelEn": "12 passes",
        "labelEs": "12 pasadas",
        "noteEn": "The lower end of real practice. The ratio starts to move and the gap to the ideal bound is wide.",
        "noteEs": "El extremo bajo de la práctica real. La razón empieza a moverse y la brecha con la cota ideal es amplia.",
        "overrides": {
          "nPasses": 12
        }
      },
      {
        "id": "p24",
        "labelEn": "24 passes",
        "labelEs": "24 pasadas",
        "noteEn": "The reference regime, and the default the other axes are compared at.",
        "noteEs": "El régimen de referencia, y el valor con el que se comparan los otros ejes.",
        "overrides": {
          "nPasses": 24
        }
      },
      {
        "id": "p36",
        "labelEn": "36 passes",
        "labelEs": "36 pasadas",
        "noteEn": "Common on a long yard. The returns are still real, but the curve is already bending away from the 1/N line rather than tracking it.",
        "noteEs": "Habitual en una cancha larga. El retorno sigue siendo real, pero la curva ya se aleja de la línea 1/N en vez de seguirla.",
        "overrides": {
          "nPasses": 36
        }
      },
      {
        "id": "p48",
        "labelEn": "48 passes",
        "labelEs": "48 pasadas",
        "noteEn": "Diminishing returns: the layers are thin enough that the input's own autocorrelation, not the count, is what limits the result.",
        "noteEs": "Retornos decrecientes: las capas son tan delgadas que lo que limita el resultado es la autocorrelación del flujo, no el conteo.",
        "overrides": {
          "nPasses": 48
        }
      },
      {
        "id": "p64",
        "labelEn": "64 passes",
        "labelEs": "64 pasadas",
        "noteEn": "Past the useful end. Compare the achieved ratio against the 1/N line to see how little the last twenty passes bought.",
        "noteEs": "Más allá del punto útil. Comparar la razón lograda contra la línea 1/N muestra lo poco que aportaron las últimas veinte pasadas.",
        "overrides": {
          "nPasses": 64
        }
      }
    ]
  },
  {
    "id": "G02_windrow",
    "category": "stacking-geometry",
    "reason": "The same longitudinal travel with the deposition axis slewing across three cords, so the toe bias is spread over several crests instead of two flanks.",
    "expectedBand": "VRR near chevron; a smaller toe-minus-apex coarse delta than chevron at the same Sr",
    "killCriterion": "If the segregation index is not below chevron's, the lateral spreading is not reaching the ledger",
    "realOrSynthetic": "synthetic",
    "split": "holdout",
    "stacking": "windrow",
    "reclaim": "fullface",
    "nPasses": 24,
    "reclaimRate": 1.0,
    "cutTonnes": 900.0,
    "startFraction": 0.35,
    "sr": 1.0,
    "reposeDeg": 37.0,
    "reposeCoarseDeg": 37.0,
    "structure": "stationary",
    "rangeT": 4000.0,
    "nDumps": 320,
    "coarseSd": 0.08,
    "nx": 64,
    "ny": 24,
    "cellM": 3.0,
    "tags": [],
    "variants": [
      {
        "id": "p6",
        "labelEn": "6 passes",
        "labelEs": "6 pasadas",
        "noteEn": "Too few layers to blend. The bed is a stockpile with a shape, and the ratio stays near one.",
        "noteEs": "Muy pocas capas para mezclar. La cama es un acopio con forma y la razón se queda cerca de uno.",
        "overrides": {
          "nPasses": 6
        }
      },
      {
        "id": "p12",
        "labelEn": "12 passes",
        "labelEs": "12 pasadas",
        "noteEn": "The lower end of real practice. The ratio starts to move and the gap to the ideal bound is wide.",
        "noteEs": "El extremo bajo de la práctica real. La razón empieza a moverse y la brecha con la cota ideal es amplia.",
        "overrides": {
          "nPasses": 12
        }
      },
      {
        "id": "p24",
        "labelEn": "24 passes",
        "labelEs": "24 pasadas",
        "noteEn": "The reference regime, and the default the other axes are compared at.",
        "noteEs": "El régimen de referencia, y el valor con el que se comparan los otros ejes.",
        "overrides": {
          "nPasses": 24
        }
      },
      {
        "id": "p36",
        "labelEn": "36 passes",
        "labelEs": "36 pasadas",
        "noteEn": "Common on a long yard. The returns are still real, but the curve is already bending away from the 1/N line rather than tracking it.",
        "noteEs": "Habitual en una cancha larga. El retorno sigue siendo real, pero la curva ya se aleja de la línea 1/N en vez de seguirla.",
        "overrides": {
          "nPasses": 36
        }
      },
      {
        "id": "p48",
        "labelEn": "48 passes",
        "labelEs": "48 pasadas",
        "noteEn": "Diminishing returns: the layers are thin enough that the input's own autocorrelation, not the count, is what limits the result.",
        "noteEs": "Retornos decrecientes: las capas son tan delgadas que lo que limita el resultado es la autocorrelación del flujo, no el conteo.",
        "overrides": {
          "nPasses": 48
        }
      },
      {
        "id": "p64",
        "labelEn": "64 passes",
        "labelEs": "64 pasadas",
        "noteEn": "Past the useful end. Compare the achieved ratio against the 1/N line to see how little the last twenty passes bought.",
        "noteEs": "Más allá del punto útil. Comparar la razón lograda contra la línea 1/N muestra lo poco que aportaron las últimas veinte pasadas.",
        "overrides": {
          "nPasses": 64
        }
      }
    ]
  },
  {
    "id": "G03_coneshell",
    "category": "stacking-geometry",
    "reason": "Stepping cones, each shelling over the last. The method the literature reports as unsuitable when homogenization matters, and the published anchor at VRR 0.232.",
    "expectedBand": "VRR in the 0.2 to 0.35 band, consistent with the published cone shell floor",
    "killCriterion": "If VRR lands below 0.15 this method is blending far better than any published result, which means the cut is crossing layers the geometry should not expose",
    "realOrSynthetic": "synthetic",
    "split": "holdout",
    "stacking": "coneshell",
    "reclaim": "fullface",
    "nPasses": 24,
    "reclaimRate": 1.0,
    "cutTonnes": 900.0,
    "startFraction": 0.35,
    "sr": 1.0,
    "reposeDeg": 37.0,
    "reposeCoarseDeg": 37.0,
    "structure": "stationary",
    "rangeT": 4000.0,
    "nDumps": 320,
    "coarseSd": 0.08,
    "nx": 64,
    "ny": 24,
    "cellM": 3.0,
    "tags": [
      "anchored"
    ],
    "variants": [
      {
        "id": "p6",
        "labelEn": "6 passes",
        "labelEs": "6 pasadas",
        "noteEn": "Too few layers to blend. The bed is a stockpile with a shape, and the ratio stays near one.",
        "noteEs": "Muy pocas capas para mezclar. La cama es un acopio con forma y la razón se queda cerca de uno.",
        "overrides": {
          "nPasses": 6
        }
      },
      {
        "id": "p12",
        "labelEn": "12 passes",
        "labelEs": "12 pasadas",
        "noteEn": "The lower end of real practice. The ratio starts to move and the gap to the ideal bound is wide.",
        "noteEs": "El extremo bajo de la práctica real. La razón empieza a moverse y la brecha con la cota ideal es amplia.",
        "overrides": {
          "nPasses": 12
        }
      },
      {
        "id": "p24",
        "labelEn": "24 passes",
        "labelEs": "24 pasadas",
        "noteEn": "The reference regime, and the default the other axes are compared at.",
        "noteEs": "El régimen de referencia, y el valor con el que se comparan los otros ejes.",
        "overrides": {
          "nPasses": 24
        }
      },
      {
        "id": "p36",
        "labelEn": "36 passes",
        "labelEs": "36 pasadas",
        "noteEn": "Common on a long yard. The returns are still real, but the curve is already bending away from the 1/N line rather than tracking it.",
        "noteEs": "Habitual en una cancha larga. El retorno sigue siendo real, pero la curva ya se aleja de la línea 1/N en vez de seguirla.",
        "overrides": {
          "nPasses": 36
        }
      },
      {
        "id": "p48",
        "labelEn": "48 passes",
        "labelEs": "48 pasadas",
        "noteEn": "Diminishing returns: the layers are thin enough that the input's own autocorrelation, not the count, is what limits the result.",
        "noteEs": "Retornos decrecientes: las capas son tan delgadas que lo que limita el resultado es la autocorrelación del flujo, no el conteo.",
        "overrides": {
          "nPasses": 48
        }
      },
      {
        "id": "p64",
        "labelEn": "64 passes",
        "labelEs": "64 pasadas",
        "noteEn": "Past the useful end. Compare the achieved ratio against the 1/N line to see how little the last twenty passes bought.",
        "noteEs": "Más allá del punto útil. Comparar la razón lograda contra la línea 1/N muestra lo poco que aportaron las últimas veinte pasadas.",
        "overrides": {
          "nPasses": 64
        }
      }
    ]
  },
  {
    "id": "G04_strata",
    "category": "stacking-geometry",
    "reason": "Inclined layers built against one flank. Intermediate blending, and the case that shows layer inclination is an operating variable in its own right.",
    "expectedBand": "VRR between chevron and cone shell",
    "killCriterion": "If VRR is outside the chevron-to-cone-shell interval, the lean is not producing inclined layers",
    "realOrSynthetic": "synthetic",
    "split": "holdout",
    "stacking": "strata",
    "reclaim": "fullface",
    "nPasses": 24,
    "reclaimRate": 1.0,
    "cutTonnes": 900.0,
    "startFraction": 0.35,
    "sr": 1.0,
    "reposeDeg": 37.0,
    "reposeCoarseDeg": 37.0,
    "structure": "stationary",
    "rangeT": 4000.0,
    "nDumps": 320,
    "coarseSd": 0.08,
    "nx": 64,
    "ny": 24,
    "cellM": 3.0,
    "tags": [],
    "variants": [
      {
        "id": "p6",
        "labelEn": "6 passes",
        "labelEs": "6 pasadas",
        "noteEn": "Too few layers to blend. The bed is a stockpile with a shape, and the ratio stays near one.",
        "noteEs": "Muy pocas capas para mezclar. La cama es un acopio con forma y la razón se queda cerca de uno.",
        "overrides": {
          "nPasses": 6
        }
      },
      {
        "id": "p12",
        "labelEn": "12 passes",
        "labelEs": "12 pasadas",
        "noteEn": "The lower end of real practice. The ratio starts to move and the gap to the ideal bound is wide.",
        "noteEs": "El extremo bajo de la práctica real. La razón empieza a moverse y la brecha con la cota ideal es amplia.",
        "overrides": {
          "nPasses": 12
        }
      },
      {
        "id": "p24",
        "labelEn": "24 passes",
        "labelEs": "24 pasadas",
        "noteEn": "The reference regime, and the default the other axes are compared at.",
        "noteEs": "El régimen de referencia, y el valor con el que se comparan los otros ejes.",
        "overrides": {
          "nPasses": 24
        }
      },
      {
        "id": "p36",
        "labelEn": "36 passes",
        "labelEs": "36 pasadas",
        "noteEn": "Common on a long yard. The returns are still real, but the curve is already bending away from the 1/N line rather than tracking it.",
        "noteEs": "Habitual en una cancha larga. El retorno sigue siendo real, pero la curva ya se aleja de la línea 1/N en vez de seguirla.",
        "overrides": {
          "nPasses": 36
        }
      },
      {
        "id": "p48",
        "labelEn": "48 passes",
        "labelEs": "48 pasadas",
        "noteEn": "Diminishing returns: the layers are thin enough that the input's own autocorrelation, not the count, is what limits the result.",
        "noteEs": "Retornos decrecientes: las capas son tan delgadas que lo que limita el resultado es la autocorrelación del flujo, no el conteo.",
        "overrides": {
          "nPasses": 48
        }
      },
      {
        "id": "p64",
        "labelEn": "64 passes",
        "labelEs": "64 pasadas",
        "noteEn": "Past the useful end. Compare the achieved ratio against the 1/N line to see how little the last twenty passes bought.",
        "noteEs": "Más allá del punto útil. Comparar la razón lograda contra la línea 1/N muestra lo poco que aportaron las últimas veinte pasadas.",
        "overrides": {
          "nPasses": 64
        }
      }
    ]
  },
  {
    "id": "G05_chevcon",
    "category": "stacking-geometry",
    "reason": "Chevron travel with the pattern advancing along the pile. The best-blending industrial method and the second published anchor, at VRR 0.121 with about a ten to one variance reduction reported for chevcon reclaimed full-face.",
    "expectedBand": "The lowest VRR of the five, at or below about 0.15",
    "killCriterion": "If VRR(G05) is not the lowest of the five geometries, the ordering the whole literature agrees on has not been reproduced and the engine is wrong",
    "realOrSynthetic": "synthetic",
    "split": "holdout",
    "stacking": "chevcon",
    "reclaim": "fullface",
    "nPasses": 24,
    "reclaimRate": 1.0,
    "cutTonnes": 900.0,
    "startFraction": 0.35,
    "sr": 1.0,
    "reposeDeg": 37.0,
    "reposeCoarseDeg": 37.0,
    "structure": "stationary",
    "rangeT": 4000.0,
    "nDumps": 320,
    "coarseSd": 0.08,
    "nx": 64,
    "ny": 24,
    "cellM": 3.0,
    "tags": [
      "anchored",
      "best"
    ],
    "variants": [
      {
        "id": "p6",
        "labelEn": "6 passes",
        "labelEs": "6 pasadas",
        "noteEn": "Too few layers to blend. The bed is a stockpile with a shape, and the ratio stays near one.",
        "noteEs": "Muy pocas capas para mezclar. La cama es un acopio con forma y la razón se queda cerca de uno.",
        "overrides": {
          "nPasses": 6
        }
      },
      {
        "id": "p12",
        "labelEn": "12 passes",
        "labelEs": "12 pasadas",
        "noteEn": "The lower end of real practice. The ratio starts to move and the gap to the ideal bound is wide.",
        "noteEs": "El extremo bajo de la práctica real. La razón empieza a moverse y la brecha con la cota ideal es amplia.",
        "overrides": {
          "nPasses": 12
        }
      },
      {
        "id": "p24",
        "labelEn": "24 passes",
        "labelEs": "24 pasadas",
        "noteEn": "The reference regime, and the default the other axes are compared at.",
        "noteEs": "El régimen de referencia, y el valor con el que se comparan los otros ejes.",
        "overrides": {
          "nPasses": 24
        }
      },
      {
        "id": "p36",
        "labelEn": "36 passes",
        "labelEs": "36 pasadas",
        "noteEn": "Common on a long yard. The returns are still real, but the curve is already bending away from the 1/N line rather than tracking it.",
        "noteEs": "Habitual en una cancha larga. El retorno sigue siendo real, pero la curva ya se aleja de la línea 1/N en vez de seguirla.",
        "overrides": {
          "nPasses": 36
        }
      },
      {
        "id": "p48",
        "labelEn": "48 passes",
        "labelEs": "48 pasadas",
        "noteEn": "Diminishing returns: the layers are thin enough that the input's own autocorrelation, not the count, is what limits the result.",
        "noteEs": "Retornos decrecientes: las capas son tan delgadas que lo que limita el resultado es la autocorrelación del flujo, no el conteo.",
        "overrides": {
          "nPasses": 48
        }
      },
      {
        "id": "p64",
        "labelEn": "64 passes",
        "labelEs": "64 pasadas",
        "noteEn": "Past the useful end. Compare the achieved ratio against the 1/N line to see how little the last twenty passes bought.",
        "noteEs": "Más allá del punto útil. Comparar la razón lograda contra la línea 1/N muestra lo poco que aportaron las últimas veinte pasadas.",
        "overrides": {
          "nPasses": 64
        }
      }
    ]
  },
  {
    "id": "R02_bucketwheel",
    "category": "reclaim-method",
    "reason": "A slewing bucket wheel cutting a bench: a third of the width, upper half of each column. It crosses the exposed layers and misses the rest.",
    "expectedBand": "VRR above full-face and below end reclaim",
    "killCriterion": "If VRR(R02) is at or below VRR(G01) the bench is somehow crossing more layers than a full-face cut, which is geometrically impossible",
    "realOrSynthetic": "synthetic",
    "split": "holdout",
    "stacking": "chevron",
    "reclaim": "bucketwheel",
    "nPasses": 24,
    "reclaimRate": 1.0,
    "cutTonnes": 900.0,
    "startFraction": 0.35,
    "sr": 1.0,
    "reposeDeg": 37.0,
    "reposeCoarseDeg": 37.0,
    "structure": "stationary",
    "rangeT": 4000.0,
    "nDumps": 320,
    "coarseSd": 0.08,
    "nx": 64,
    "ny": 24,
    "cellM": 3.0,
    "tags": [],
    "variants": [
      {
        "id": "c300",
        "labelEn": "300 t",
        "labelEs": "300 t",
        "noteEn": "A small parcel. The reclaim geometry shows through most clearly here, because a small cut cannot integrate over enough of the face to hide it.",
        "noteEs": "Un parcel pequeño. La geometría de recuperación se nota al máximo, porque un corte pequeño no alcanza a integrar suficiente frente como para disimularla.",
        "overrides": {
          "cutTonnes": 300.0
        }
      },
      {
        "id": "c600",
        "labelEn": "600 t",
        "labelEs": "600 t",
        "noteEn": "A short fleet cycle: roughly three truck loads to the plant at a time. Still small enough that a shallow-reaching machine has to walk to fill it.",
        "noteEs": "Un ciclo corto de flota: del orden de tres cargas de camión hacia la planta a la vez. Todavía pequeño como para que una máquina de poco alcance deba desplazarse para completarlo.",
        "overrides": {
          "cutTonnes": 600.0
        }
      },
      {
        "id": "c900",
        "labelEn": "900 t",
        "labelEs": "900 t",
        "noteEn": "The reference parcel, and the default of the other axes.",
        "noteEs": "El parcel de referencia, y el valor por defecto de los otros ejes.",
        "overrides": {
          "cutTonnes": 900.0
        }
      },
      {
        "id": "c1200",
        "labelEn": "1200 t",
        "labelEs": "1200 t",
        "noteEn": "A larger draw. More of the face per cut, so the machines start to look alike.",
        "noteEs": "Una saca mayor. Más frente por corte, así que las máquinas empiezan a parecerse.",
        "overrides": {
          "cutTonnes": 1200.0
        }
      },
      {
        "id": "c1800",
        "labelEn": "1800 t",
        "labelEs": "1800 t",
        "noteEn": "A shift-scale parcel. The reclaim axis is now mostly averaged away.",
        "noteEs": "Un parcel a escala de turno. El eje de recuperación queda casi promediado.",
        "overrides": {
          "cutTonnes": 1800.0
        }
      },
      {
        "id": "c2400",
        "labelEn": "2400 t",
        "labelEs": "2400 t",
        "noteEn": "Large enough that the cut spans several stations, which is a different machine duty from the one the geometry describes; read the layer count rather than the ratio here.",
        "noteEs": "Suficientemente grande para que el corte abarque varias estaciones, que es un servicio distinto del que describe la geometría; aquí conviene leer el conteo de capas y no la razón.",
        "overrides": {
          "cutTonnes": 2400.0
        }
      }
    ]
  },
  {
    "id": "R03_end",
    "category": "reclaim-method",
    "reason": "End reclaim working the exposed end face, which over-represents the most recently stacked material.",
    "expectedBand": "VRR well above full-face; the reclaimed stream visibly lags the input rather than averaging it",
    "killCriterion": "If VRR(R03) is below VRR(R02) the recency bias is not reaching the ledger",
    "realOrSynthetic": "synthetic",
    "split": "holdout",
    "stacking": "chevron",
    "reclaim": "end",
    "nPasses": 24,
    "reclaimRate": 1.0,
    "cutTonnes": 900.0,
    "startFraction": 0.35,
    "sr": 1.0,
    "reposeDeg": 37.0,
    "reposeCoarseDeg": 37.0,
    "structure": "stationary",
    "rangeT": 4000.0,
    "nDumps": 320,
    "coarseSd": 0.08,
    "nx": 64,
    "ny": 24,
    "cellM": 3.0,
    "tags": [],
    "variants": [
      {
        "id": "c300",
        "labelEn": "300 t",
        "labelEs": "300 t",
        "noteEn": "A small parcel. The reclaim geometry shows through most clearly here, because a small cut cannot integrate over enough of the face to hide it.",
        "noteEs": "Un parcel pequeño. La geometría de recuperación se nota al máximo, porque un corte pequeño no alcanza a integrar suficiente frente como para disimularla.",
        "overrides": {
          "cutTonnes": 300.0
        }
      },
      {
        "id": "c600",
        "labelEn": "600 t",
        "labelEs": "600 t",
        "noteEn": "A short fleet cycle: roughly three truck loads to the plant at a time. Still small enough that a shallow-reaching machine has to walk to fill it.",
        "noteEs": "Un ciclo corto de flota: del orden de tres cargas de camión hacia la planta a la vez. Todavía pequeño como para que una máquina de poco alcance deba desplazarse para completarlo.",
        "overrides": {
          "cutTonnes": 600.0
        }
      },
      {
        "id": "c900",
        "labelEn": "900 t",
        "labelEs": "900 t",
        "noteEn": "The reference parcel, and the default of the other axes.",
        "noteEs": "El parcel de referencia, y el valor por defecto de los otros ejes.",
        "overrides": {
          "cutTonnes": 900.0
        }
      },
      {
        "id": "c1200",
        "labelEn": "1200 t",
        "labelEs": "1200 t",
        "noteEn": "A larger draw. More of the face per cut, so the machines start to look alike.",
        "noteEs": "Una saca mayor. Más frente por corte, así que las máquinas empiezan a parecerse.",
        "overrides": {
          "cutTonnes": 1200.0
        }
      },
      {
        "id": "c1800",
        "labelEn": "1800 t",
        "labelEs": "1800 t",
        "noteEn": "A shift-scale parcel. The reclaim axis is now mostly averaged away.",
        "noteEs": "Un parcel a escala de turno. El eje de recuperación queda casi promediado.",
        "overrides": {
          "cutTonnes": 1800.0
        }
      },
      {
        "id": "c2400",
        "labelEn": "2400 t",
        "labelEs": "2400 t",
        "noteEn": "Large enough that the cut spans several stations, which is a different machine duty from the one the geometry describes; read the layer count rather than the ratio here.",
        "noteEs": "Suficientemente grande para que el corte abarque varias estaciones, que es un servicio distinto del que describe la geometría; aquí conviene leer el conteo de capas y no la razón.",
        "overrides": {
          "cutTonnes": 2400.0
        }
      }
    ]
  },
  {
    "id": "R04_loader",
    "category": "reclaim-method",
    "reason": "Scattered front-end loader bites from the top of a few accessible columns. Fewest layers, least spatial averaging, and the real run-of-mine pad case rather than the blending-bed ideal.",
    "expectedBand": "The worst VRR of the reclaim axis, plausibly close to 1 (little or no blending)",
    "killCriterion": "If VRR(R04) is the best of the reclaim axis the cell selection is wrong",
    "realOrSynthetic": "synthetic",
    "split": "holdout",
    "stacking": "chevron",
    "reclaim": "loader",
    "nPasses": 24,
    "reclaimRate": 1.0,
    "cutTonnes": 900.0,
    "startFraction": 0.35,
    "sr": 1.0,
    "reposeDeg": 37.0,
    "reposeCoarseDeg": 37.0,
    "structure": "stationary",
    "rangeT": 4000.0,
    "nDumps": 320,
    "coarseSd": 0.08,
    "nx": 64,
    "ny": 24,
    "cellM": 3.0,
    "tags": [],
    "variants": [
      {
        "id": "c300",
        "labelEn": "300 t",
        "labelEs": "300 t",
        "noteEn": "A small parcel. The reclaim geometry shows through most clearly here, because a small cut cannot integrate over enough of the face to hide it.",
        "noteEs": "Un parcel pequeño. La geometría de recuperación se nota al máximo, porque un corte pequeño no alcanza a integrar suficiente frente como para disimularla.",
        "overrides": {
          "cutTonnes": 300.0
        }
      },
      {
        "id": "c600",
        "labelEn": "600 t",
        "labelEs": "600 t",
        "noteEn": "A short fleet cycle: roughly three truck loads to the plant at a time. Still small enough that a shallow-reaching machine has to walk to fill it.",
        "noteEs": "Un ciclo corto de flota: del orden de tres cargas de camión hacia la planta a la vez. Todavía pequeño como para que una máquina de poco alcance deba desplazarse para completarlo.",
        "overrides": {
          "cutTonnes": 600.0
        }
      },
      {
        "id": "c900",
        "labelEn": "900 t",
        "labelEs": "900 t",
        "noteEn": "The reference parcel, and the default of the other axes.",
        "noteEs": "El parcel de referencia, y el valor por defecto de los otros ejes.",
        "overrides": {
          "cutTonnes": 900.0
        }
      },
      {
        "id": "c1200",
        "labelEn": "1200 t",
        "labelEs": "1200 t",
        "noteEn": "A larger draw. More of the face per cut, so the machines start to look alike.",
        "noteEs": "Una saca mayor. Más frente por corte, así que las máquinas empiezan a parecerse.",
        "overrides": {
          "cutTonnes": 1200.0
        }
      },
      {
        "id": "c1800",
        "labelEn": "1800 t",
        "labelEs": "1800 t",
        "noteEn": "A shift-scale parcel. The reclaim axis is now mostly averaged away.",
        "noteEs": "Un parcel a escala de turno. El eje de recuperación queda casi promediado.",
        "overrides": {
          "cutTonnes": 1800.0
        }
      },
      {
        "id": "c2400",
        "labelEn": "2400 t",
        "labelEs": "2400 t",
        "noteEn": "Large enough that the cut spans several stations, which is a different machine duty from the one the geometry describes; read the layer count rather than the ratio here.",
        "noteEs": "Suficientemente grande para que el corte abarque varias estaciones, que es un servicio distinto del que describe la geometría; aquí conviene leer el conteo de capas y no la razón.",
        "overrides": {
          "cutTonnes": 2400.0
        }
      }
    ]
  },
  {
    "id": "V01_short_range",
    "category": "input-variability",
    "reason": "Grade correlation range much shorter than the tonnage in one layer, so successive layers are nearly independent. This is the case where the independent-layer bound is nearly attainable.",
    "expectedBand": "Blending efficiency against the 1/N bound the highest of the four V cases",
    "killCriterion": "If the efficiency here is not the highest of V01 to V04, the variogram range is not reaching the simulation",
    "realOrSynthetic": "synthetic",
    "split": "holdout",
    "stacking": "chevron",
    "reclaim": "fullface",
    "nPasses": 24,
    "reclaimRate": 1.0,
    "cutTonnes": 900.0,
    "startFraction": 0.35,
    "sr": 1.0,
    "reposeDeg": 37.0,
    "reposeCoarseDeg": 37.0,
    "structure": "short_range",
    "rangeT": 4000.0,
    "nDumps": 320,
    "coarseSd": 0.08,
    "nx": 64,
    "ny": 24,
    "cellM": 3.0,
    "tags": [],
    "variants": [
      {
        "id": "r200",
        "labelEn": "200 t",
        "labelEs": "200 t",
        "noteEn": "Correlation shorter than a single truck. The layers are effectively independent and the achieved ratio can approach the 1/N bound.",
        "noteEs": "Correlación más corta que un solo camión. Las capas son independientes en la práctica y la razón lograda puede acercarse a la cota 1/N.",
        "overrides": {
          "rangeT": 200.0
        }
      },
      {
        "id": "r1000",
        "labelEn": "1 kt",
        "labelEs": "1 kt",
        "noteEn": "Still well inside one layer's tonnage, so consecutive layers are close to independent and the bed still recovers most of what the bound allows.",
        "noteEs": "Todavía bien dentro del tonelaje de una capa, así que las capas consecutivas son casi independientes y la cama aún recupera la mayor parte de lo que permite la cota.",
        "overrides": {
          "rangeT": 1000.0
        }
      },
      {
        "id": "r4000",
        "labelEn": "4 kt",
        "labelEs": "4 kt",
        "noteEn": "The reference structure, comparable to one layer's tonnage.",
        "noteEs": "La estructura de referencia, comparable al tonelaje de una capa.",
        "overrides": {
          "rangeT": 4000.0
        }
      },
      {
        "id": "r10000",
        "labelEn": "10 kt",
        "labelEs": "10 kt",
        "noteEn": "Longer than a layer. Consecutive layers now share grade and the bed recovers noticeably less than the bound promises.",
        "noteEs": "Más larga que una capa. Las capas consecutivas comparten ley y la cama recupera bastante menos de lo que promete la cota.",
        "overrides": {
          "rangeT": 10000.0
        }
      },
      {
        "id": "r20000",
        "labelEn": "20 kt",
        "labelEs": "20 kt",
        "noteEn": "Several layers per correlation length. The gap to the ideal is now the headline number.",
        "noteEs": "Varias capas por longitud de correlación. La brecha con lo ideal pasa a ser el número principal.",
        "overrides": {
          "rangeT": 20000.0
        }
      },
      {
        "id": "r40000",
        "labelEn": "40 kt",
        "labelEs": "40 kt",
        "noteEn": "Longer than the whole build. Every layer carries nearly the same grade, so the bed has almost nothing to average and the ratio approaches one.",
        "noteEs": "Más larga que toda la construcción. Cada capa lleva casi la misma ley, la cama casi no tiene nada que promediar y la razón se acerca a uno.",
        "overrides": {
          "rangeT": 40000.0
        }
      }
    ]
  },
  {
    "id": "V02_long_range",
    "category": "input-variability",
    "reason": "Correlation range longer than the whole pile, so every layer carries nearly the same grade and the bed has almost nothing to average. Ships as a headline case rather than being buried, because it is the honest one.",
    "expectedBand": "VRR close to 1 and efficiency far below V01; the bed barely helps",
    "killCriterion": "If VRR here is comparable to V01 the input autocorrelation is being ignored somewhere",
    "realOrSynthetic": "synthetic",
    "split": "holdout",
    "stacking": "chevron",
    "reclaim": "fullface",
    "nPasses": 24,
    "reclaimRate": 1.0,
    "cutTonnes": 900.0,
    "startFraction": 0.35,
    "sr": 1.0,
    "reposeDeg": 37.0,
    "reposeCoarseDeg": 37.0,
    "structure": "long_range",
    "rangeT": 4000.0,
    "nDumps": 320,
    "coarseSd": 0.08,
    "nx": 64,
    "ny": 24,
    "cellM": 3.0,
    "tags": [
      "honest"
    ],
    "variants": [
      {
        "id": "r200",
        "labelEn": "200 t",
        "labelEs": "200 t",
        "noteEn": "Correlation shorter than a single truck. The layers are effectively independent and the achieved ratio can approach the 1/N bound.",
        "noteEs": "Correlación más corta que un solo camión. Las capas son independientes en la práctica y la razón lograda puede acercarse a la cota 1/N.",
        "overrides": {
          "rangeT": 200.0
        }
      },
      {
        "id": "r1000",
        "labelEn": "1 kt",
        "labelEs": "1 kt",
        "noteEn": "Still well inside one layer's tonnage, so consecutive layers are close to independent and the bed still recovers most of what the bound allows.",
        "noteEs": "Todavía bien dentro del tonelaje de una capa, así que las capas consecutivas son casi independientes y la cama aún recupera la mayor parte de lo que permite la cota.",
        "overrides": {
          "rangeT": 1000.0
        }
      },
      {
        "id": "r4000",
        "labelEn": "4 kt",
        "labelEs": "4 kt",
        "noteEn": "The reference structure, comparable to one layer's tonnage.",
        "noteEs": "La estructura de referencia, comparable al tonelaje de una capa.",
        "overrides": {
          "rangeT": 4000.0
        }
      },
      {
        "id": "r10000",
        "labelEn": "10 kt",
        "labelEs": "10 kt",
        "noteEn": "Longer than a layer. Consecutive layers now share grade and the bed recovers noticeably less than the bound promises.",
        "noteEs": "Más larga que una capa. Las capas consecutivas comparten ley y la cama recupera bastante menos de lo que promete la cota.",
        "overrides": {
          "rangeT": 10000.0
        }
      },
      {
        "id": "r20000",
        "labelEn": "20 kt",
        "labelEs": "20 kt",
        "noteEn": "Several layers per correlation length. The gap to the ideal is now the headline number.",
        "noteEs": "Varias capas por longitud de correlación. La brecha con lo ideal pasa a ser el número principal.",
        "overrides": {
          "rangeT": 20000.0
        }
      },
      {
        "id": "r40000",
        "labelEn": "40 kt",
        "labelEs": "40 kt",
        "noteEn": "Longer than the whole build. Every layer carries nearly the same grade, so the bed has almost nothing to average and the ratio approaches one.",
        "noteEs": "Más larga que toda la construcción. Cada capa lleva casi la misma ley, la cama casi no tiene nada que promediar y la razón se acerca a uno.",
        "overrides": {
          "rangeT": 40000.0
        }
      }
    ]
  },
  {
    "id": "V03_trending",
    "category": "input-variability",
    "reason": "A linear grade drift across the shift on top of the correlated field. The mean moves, so variance reduction on the whole record becomes a misleading summary of what the plant sees.",
    "expectedBand": "VRR may look acceptable while the reclaimed mean drifts; the drift must be visible on the stream plot",
    "killCriterion": "If the reclaimed mean does not drift with the input, the trend is not being generated",
    "realOrSynthetic": "synthetic",
    "split": "holdout",
    "stacking": "chevron",
    "reclaim": "fullface",
    "nPasses": 24,
    "reclaimRate": 1.0,
    "cutTonnes": 900.0,
    "startFraction": 0.35,
    "sr": 1.0,
    "reposeDeg": 37.0,
    "reposeCoarseDeg": 37.0,
    "structure": "trending",
    "rangeT": 4000.0,
    "nDumps": 320,
    "coarseSd": 0.08,
    "nx": 64,
    "ny": 24,
    "cellM": 3.0,
    "tags": [
      "honest"
    ],
    "variants": [
      {
        "id": "r200",
        "labelEn": "200 t",
        "labelEs": "200 t",
        "noteEn": "Correlation shorter than a single truck. The layers are effectively independent and the achieved ratio can approach the 1/N bound.",
        "noteEs": "Correlación más corta que un solo camión. Las capas son independientes en la práctica y la razón lograda puede acercarse a la cota 1/N.",
        "overrides": {
          "rangeT": 200.0
        }
      },
      {
        "id": "r1000",
        "labelEn": "1 kt",
        "labelEs": "1 kt",
        "noteEn": "Still well inside one layer's tonnage, so consecutive layers are close to independent and the bed still recovers most of what the bound allows.",
        "noteEs": "Todavía bien dentro del tonelaje de una capa, así que las capas consecutivas son casi independientes y la cama aún recupera la mayor parte de lo que permite la cota.",
        "overrides": {
          "rangeT": 1000.0
        }
      },
      {
        "id": "r4000",
        "labelEn": "4 kt",
        "labelEs": "4 kt",
        "noteEn": "The reference structure, comparable to one layer's tonnage.",
        "noteEs": "La estructura de referencia, comparable al tonelaje de una capa.",
        "overrides": {
          "rangeT": 4000.0
        }
      },
      {
        "id": "r10000",
        "labelEn": "10 kt",
        "labelEs": "10 kt",
        "noteEn": "Longer than a layer. Consecutive layers now share grade and the bed recovers noticeably less than the bound promises.",
        "noteEs": "Más larga que una capa. Las capas consecutivas comparten ley y la cama recupera bastante menos de lo que promete la cota.",
        "overrides": {
          "rangeT": 10000.0
        }
      },
      {
        "id": "r20000",
        "labelEn": "20 kt",
        "labelEs": "20 kt",
        "noteEn": "Several layers per correlation length. The gap to the ideal is now the headline number.",
        "noteEs": "Varias capas por longitud de correlación. La brecha con lo ideal pasa a ser el número principal.",
        "overrides": {
          "rangeT": 20000.0
        }
      },
      {
        "id": "r40000",
        "labelEn": "40 kt",
        "labelEs": "40 kt",
        "noteEn": "Longer than the whole build. Every layer carries nearly the same grade, so the bed has almost nothing to average and the ratio approaches one.",
        "noteEs": "Más larga que toda la construcción. Cada capa lleva casi la misma ley, la cama casi no tiene nada que promediar y la razón se acerca a uno.",
        "overrides": {
          "rangeT": 40000.0
        }
      }
    ]
  },
  {
    "id": "V04_bimodal",
    "category": "input-variability",
    "reason": "Two ore types arriving in runs, as they would from two dig faces. The reclaimed histogram stays bimodal even when the VRR looks respectable, which is why the distribution has to be shown and not only its second moment.",
    "expectedBand": "Reclaimed grade histogram visibly bimodal despite a VRR below 0.4",
    "killCriterion": "If the reclaimed histogram is unimodal the mixture is not surviving into the cuts and the generator is wrong",
    "realOrSynthetic": "synthetic",
    "split": "holdout",
    "stacking": "chevron",
    "reclaim": "fullface",
    "nPasses": 24,
    "reclaimRate": 1.0,
    "cutTonnes": 900.0,
    "startFraction": 0.35,
    "sr": 1.0,
    "reposeDeg": 37.0,
    "reposeCoarseDeg": 37.0,
    "structure": "bimodal",
    "rangeT": 4000.0,
    "nDumps": 320,
    "coarseSd": 0.08,
    "nx": 64,
    "ny": 24,
    "cellM": 3.0,
    "tags": [
      "honest"
    ],
    "variants": [
      {
        "id": "r200",
        "labelEn": "200 t",
        "labelEs": "200 t",
        "noteEn": "Correlation shorter than a single truck. The layers are effectively independent and the achieved ratio can approach the 1/N bound.",
        "noteEs": "Correlación más corta que un solo camión. Las capas son independientes en la práctica y la razón lograda puede acercarse a la cota 1/N.",
        "overrides": {
          "rangeT": 200.0
        }
      },
      {
        "id": "r1000",
        "labelEn": "1 kt",
        "labelEs": "1 kt",
        "noteEn": "Still well inside one layer's tonnage, so consecutive layers are close to independent and the bed still recovers most of what the bound allows.",
        "noteEs": "Todavía bien dentro del tonelaje de una capa, así que las capas consecutivas son casi independientes y la cama aún recupera la mayor parte de lo que permite la cota.",
        "overrides": {
          "rangeT": 1000.0
        }
      },
      {
        "id": "r4000",
        "labelEn": "4 kt",
        "labelEs": "4 kt",
        "noteEn": "The reference structure, comparable to one layer's tonnage.",
        "noteEs": "La estructura de referencia, comparable al tonelaje de una capa.",
        "overrides": {
          "rangeT": 4000.0
        }
      },
      {
        "id": "r10000",
        "labelEn": "10 kt",
        "labelEs": "10 kt",
        "noteEn": "Longer than a layer. Consecutive layers now share grade and the bed recovers noticeably less than the bound promises.",
        "noteEs": "Más larga que una capa. Las capas consecutivas comparten ley y la cama recupera bastante menos de lo que promete la cota.",
        "overrides": {
          "rangeT": 10000.0
        }
      },
      {
        "id": "r20000",
        "labelEn": "20 kt",
        "labelEs": "20 kt",
        "noteEn": "Several layers per correlation length. The gap to the ideal is now the headline number.",
        "noteEs": "Varias capas por longitud de correlación. La brecha con lo ideal pasa a ser el número principal.",
        "overrides": {
          "rangeT": 20000.0
        }
      },
      {
        "id": "r40000",
        "labelEn": "40 kt",
        "labelEs": "40 kt",
        "noteEn": "Longer than the whole build. Every layer carries nearly the same grade, so the bed has almost nothing to average and the ratio approaches one.",
        "noteEs": "Más larga que toda la construcción. Cada capa lleva casi la misma ley, la cama casi no tiene nada que promediar y la razón se acerca a uno.",
        "overrides": {
          "rangeT": 40000.0
        }
      }
    ]
  },
  {
    "id": "S01_strong_sieving",
    "category": "segregation-regime",
    "reason": "A wide size distribution with a high segregation number, so kinetic sieving drives coarse to the toe strongly enough to bias what each reclaim cut contains.",
    "expectedBand": "A large positive toe-minus-apex coarse-fraction delta; cut composition varying with the reclaim front position",
    "killCriterion": "If the segregation index is near zero at Sr = 4 the flowing-layer solver is not coupled to the ledger",
    "realOrSynthetic": "synthetic",
    "split": "holdout",
    "stacking": "chevron",
    "reclaim": "fullface",
    "nPasses": 24,
    "reclaimRate": 1.0,
    "cutTonnes": 900.0,
    "startFraction": 0.35,
    "sr": 4.0,
    "reposeDeg": 37.0,
    "reposeCoarseDeg": 37.0,
    "structure": "stationary",
    "rangeT": 4000.0,
    "nDumps": 320,
    "coarseSd": 0.16,
    "nx": 64,
    "ny": 24,
    "cellM": 3.0,
    "tags": [
      "segregation"
    ],
    "variants": [
      {
        "id": "s00",
        "labelEn": "Sr = 0",
        "labelEs": "Sr = 0",
        "noteEn": "Kinetic sieving switched off. The size split rides with the material untouched, which is the negative control: any sorting visible here would be a solver artefact.",
        "noteEs": "Tamizado cinético apagado. La separación por tamaño viaja con el material sin tocarse, que es el control negativo: cualquier clasificación visible aquí sería un artefacto del solver.",
        "overrides": {
          "sr": 0.0
        }
      },
      {
        "id": "s05",
        "labelEn": "Sr = 0.5",
        "labelEs": "Sr = 0.5",
        "noteEn": "Weak sieving. The toe is measurably coarser than the apex but the effect is small.",
        "noteEs": "Tamizado débil. El pie es medible más grueso que el ápice, pero el efecto es pequeño.",
        "overrides": {
          "sr": 0.5
        }
      },
      {
        "id": "s10",
        "labelEn": "Sr = 1",
        "labelEs": "Sr = 1",
        "noteEn": "The reference regime, near the knee of the response.",
        "noteEs": "El régimen de referencia, cerca del codo de la respuesta.",
        "overrides": {
          "sr": 1.0
        }
      },
      {
        "id": "s20",
        "labelEn": "Sr = 2",
        "labelEs": "Sr = 2",
        "noteEn": "Strong sieving, already close to saturated: the flowing layer separates almost completely within the first few bands of the avalanche.",
        "noteEs": "Tamizado fuerte, ya cerca de la saturación: la capa fluyente se separa casi por completo dentro de las primeras bandas de la avalancha.",
        "overrides": {
          "sr": 2.0
        }
      },
      {
        "id": "s40",
        "labelEn": "Sr = 4",
        "labelEs": "Sr = 4",
        "noteEn": "Saturated. The segregation index barely moves from Sr = 2, which is the model's own prediction and not a numerical limit.",
        "noteEs": "Saturado. El índice de segregación casi no se mueve respecto de Sr = 2, que es la predicción del propio modelo y no un límite numérico.",
        "overrides": {
          "sr": 4.0
        }
      },
      {
        "id": "s80",
        "labelEn": "Sr = 8",
        "labelEs": "Sr = 8",
        "noteEn": "Past saturation, kept so the flat top of the curve is visible rather than asserted.",
        "noteEs": "Pasada la saturación, incluido para que la parte plana de la curva se vea en vez de afirmarse.",
        "overrides": {
          "sr": 8.0
        }
      }
    ]
  },
  {
    "id": "S02_stratifying",
    "category": "segregation-regime",
    "reason": "The Makse regime: the coarse species has the larger angle of repose, which is the published condition under which a poured bidisperse mixture spontaneously stratifies into alternating layers rather than merely segregating.",
    "expectedBand": "Alternating coarse and fine bands visible in the cutaway; a larger segregation index than S01 at the same Sr is not expected, the signature is the layering, not the magnitude",
    "killCriterion": "If the cutaway shows no alternation at a five degree repose difference, the coarse repose angle is not being used",
    "realOrSynthetic": "synthetic",
    "split": "holdout",
    "stacking": "coneshell",
    "reclaim": "fullface",
    "nPasses": 24,
    "reclaimRate": 1.0,
    "cutTonnes": 900.0,
    "startFraction": 0.35,
    "sr": 2.0,
    "reposeDeg": 34.0,
    "reposeCoarseDeg": 39.0,
    "structure": "stationary",
    "rangeT": 4000.0,
    "nDumps": 320,
    "coarseSd": 0.16,
    "nx": 64,
    "ny": 24,
    "cellM": 3.0,
    "tags": [
      "segregation",
      "makse"
    ],
    "variants": [
      {
        "id": "s00",
        "labelEn": "Sr = 0",
        "labelEs": "Sr = 0",
        "noteEn": "Kinetic sieving switched off. The size split rides with the material untouched, which is the negative control: any sorting visible here would be a solver artefact.",
        "noteEs": "Tamizado cinético apagado. La separación por tamaño viaja con el material sin tocarse, que es el control negativo: cualquier clasificación visible aquí sería un artefacto del solver.",
        "overrides": {
          "sr": 0.0
        }
      },
      {
        "id": "s05",
        "labelEn": "Sr = 0.5",
        "labelEs": "Sr = 0.5",
        "noteEn": "Weak sieving. The toe is measurably coarser than the apex but the effect is small.",
        "noteEs": "Tamizado débil. El pie es medible más grueso que el ápice, pero el efecto es pequeño.",
        "overrides": {
          "sr": 0.5
        }
      },
      {
        "id": "s10",
        "labelEn": "Sr = 1",
        "labelEs": "Sr = 1",
        "noteEn": "The reference regime, near the knee of the response.",
        "noteEs": "El régimen de referencia, cerca del codo de la respuesta.",
        "overrides": {
          "sr": 1.0
        }
      },
      {
        "id": "s20",
        "labelEn": "Sr = 2",
        "labelEs": "Sr = 2",
        "noteEn": "Strong sieving, already close to saturated: the flowing layer separates almost completely within the first few bands of the avalanche.",
        "noteEs": "Tamizado fuerte, ya cerca de la saturación: la capa fluyente se separa casi por completo dentro de las primeras bandas de la avalancha.",
        "overrides": {
          "sr": 2.0
        }
      },
      {
        "id": "s40",
        "labelEn": "Sr = 4",
        "labelEs": "Sr = 4",
        "noteEn": "Saturated. The segregation index barely moves from Sr = 2, which is the model's own prediction and not a numerical limit.",
        "noteEs": "Saturado. El índice de segregación casi no se mueve respecto de Sr = 2, que es la predicción del propio modelo y no un límite numérico.",
        "overrides": {
          "sr": 4.0
        }
      },
      {
        "id": "s80",
        "labelEn": "Sr = 8",
        "labelEs": "Sr = 8",
        "noteEn": "Past saturation, kept so the flat top of the curve is visible rather than asserted.",
        "noteEs": "Pasada la saturación, incluido para que la parte plana de la curva se vea en vez de afirmarse.",
        "overrides": {
          "sr": 8.0
        }
      }
    ]
  },
  {
    "id": "C01_perfect_mixer",
    "category": "control",
    "reason": "The degenerate bound: a single-cell pad with no geometry at all, so a reclaim cut is a tonnage-weighted mean of everything in the pile. The achieved VRR must equal the independent-layer bound.",
    "expectedBand": "Achieved VRR equal to 1/N within the multi-seed band",
    "killCriterion": "If the achieved VRR differs from 1/N by more than the band, the VRR implementation is wrong and every number in the product is suspect",
    "realOrSynthetic": "synthetic",
    "split": "holdout",
    "stacking": "coneshell",
    "reclaim": "fullface",
    "nPasses": 1,
    "reclaimRate": 1.0,
    "cutTonnes": 2400.0,
    "startFraction": 0.35,
    "sr": 1.0,
    "reposeDeg": 37.0,
    "reposeCoarseDeg": 37.0,
    "structure": "short_range",
    "rangeT": 4000.0,
    "nDumps": 240,
    "coarseSd": 0.08,
    "nx": 1,
    "ny": 1,
    "cellM": 40.0,
    "tags": [
      "control"
    ],
    "variants": []
  },
  {
    "id": "C02_no_segregation",
    "category": "control",
    "reason": "The negative control: the segregation number set to zero, which makes the Gray-Thornton equation degenerate to pure tracer advection. Any size sorting produced by the solver is then leaking in from somewhere it should not.",
    "expectedBand": "Every lot in the pile still carries exactly the coarse fraction of the truck it came from. The aggregate toe-minus-apex delta is not expected to be zero: different dumps carry different size distributions and land in different places, so the geometry alone produces a small spatial pattern. Measured at Sr = 0 it is about -0.01, against about +0.44 at Sr = 1, so the solver contribution is two orders of magnitude larger than the geometric one.",
    "killCriterion": "A lot whose coarse fraction differs from its source dump's by more than 1e-12 at Sr = 0 means the solver is modifying the size split when it has been switched off",
    "realOrSynthetic": "synthetic",
    "split": "holdout",
    "stacking": "chevron",
    "reclaim": "fullface",
    "nPasses": 24,
    "reclaimRate": 1.0,
    "cutTonnes": 900.0,
    "startFraction": 0.35,
    "sr": 0.0,
    "reposeDeg": 37.0,
    "reposeCoarseDeg": 37.0,
    "structure": "stationary",
    "rangeT": 4000.0,
    "nDumps": 320,
    "coarseSd": 0.16,
    "nx": 64,
    "ny": 24,
    "cellM": 3.0,
    "tags": [
      "control"
    ],
    "variants": []
  },
  {
    "id": "C03_starvation",
    "category": "control",
    "reason": "The boundary: reclaim runs at three times the stacking rate, so the pile is driven empty. A buffer model that has never been driven to its boundary has not been tested there.",
    "expectedBand": "The pile empties, the run reports starvation, and no tonnage is negative or NaN",
    "killCriterion": "A NaN, a negative tonnage, or a run that does not report starvation is a hard failure",
    "realOrSynthetic": "synthetic",
    "split": "holdout",
    "stacking": "chevron",
    "reclaim": "fullface",
    "nPasses": 24,
    "reclaimRate": 3.0,
    "cutTonnes": 900.0,
    "startFraction": 0.15,
    "sr": 1.0,
    "reposeDeg": 37.0,
    "reposeCoarseDeg": 37.0,
    "structure": "stationary",
    "rangeT": 4000.0,
    "nDumps": 320,
    "coarseSd": 0.08,
    "nx": 64,
    "ny": 24,
    "cellM": 3.0,
    "tags": [
      "control",
      "edge"
    ],
    "variants": []
  }
];

export const CASES_BY_ID: Record<string, CaseDef> = Object.fromEntries(CASES.map((c) => [c.id, c]));

export function casesByCategory(): Array<{ category: string; label: string; cases: CaseDef[] }> {
  const order = Object.keys(CATEGORY_LABELS);
  return order.map((category) => ({
    category,
    label: CATEGORY_LABELS[category],
    cases: CASES.filter((c) => c.category === category),
  })).filter((g) => g.cases.length > 0);
}

/** The variant of `c` with this id, or null for "the case as declared". */
export function variantOf(c: CaseDef, id: string | null): VariantDef | null {
  if (!id) return null;
  return c.variants.find((v) => v.id === id) ?? null;
}

/** The default regime of a case: its middle variant, or the case itself when it has none. */
export function defaultVariant(c: CaseDef): VariantDef | null {
  return c.variants.length ? c.variants[Math.floor(c.variants.length / 2)] : null;
}
