"""Offline pipeline orchestrator and command line.

The canonical bake is an explicit release operation. Tests and the CI smoke run MUST pass ``--output``
so they cannot mutate committed scientific evidence. That is not a style rule on this product line: a
pytest run once overwrote a committed bake in another repository and two releases shipped it.

    python -m pipeline.pipeline                       # every case, canonical bake
    python -m pipeline.pipeline G01_chevron --seed 7
    python -m pipeline.pipeline G01_chevron --output build/smoke
    python -m pipeline.pipeline --validate-only
"""
from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path

from . import registry
from .core.manifest import build_index
from .io.formats import write_json
from .stages import evaluate, export, infer, ingest, preprocess, validate

REPO_ROOT = Path(__file__).resolve().parents[2]
DERIVED = REPO_ROOT / "data" / "derived"
MANIFESTS = DERIVED / "manifests"
MODELS = REPO_ROOT / "models"

STAGES = ("ingest", "preprocess", "dataset", "features", "calibrate",
          "train", "infer", "evaluate", "export", "validate")

# Thirty seeds is the floor for a 5th-to-95th band that means anything; the plan commits to it, and
# the number is here rather than in a caller so a bake cannot quietly narrow it.
BAND_SEEDS = 31


@dataclass(frozen=True)
class PipelinePaths:
    root: Path
    manifests: Path
    models: Path

    @classmethod
    def from_output(cls, output: str | Path | None = None) -> PipelinePaths:
        if output is None:
            return cls(root=DERIVED, manifests=MANIFESTS, models=MODELS)
        root = Path(output).resolve()
        return cls(root=root, manifests=root / "manifests", models=root / "models")


def precompute(
    case_id: str,
    seed: int = 42,
    *,
    output_root: str | Path | None = None,
    band_seeds: int = BAND_SEEDS,
) -> tuple[dict, dict]:
    """Bake one case and return ``(manifest, matrix_row)``.

    Both are returned because the caller needs both and the simulation behind them is the expensive
    part: running it twice, once for the artifact and once for the benchmark table, would double every
    bake for nothing.
    """
    paths = PipelinePaths.from_output(output_root)
    case = registry.get_case(case_id)

    # CONTRACT 1 runs on the generated stream too, rather than the generator being trusted
    raw = case.dumps(seed)
    report = ingest.from_generated(raw)
    if not report.ok:
        raise RuntimeError(f"{case_id}: ingestion rejected every row, {report.summary()}")
    _ = preprocess.run(report.accepted)

    run_data = infer.run_case(case, seed)
    band = infer.multi_seed(case, [seed + 97 * k for k in range(band_seeds)])
    inv = evaluate.invariants(run_data)
    ctl = evaluate.control_verdict(case, run_data, band)

    manifest = export.run(
        case=case, run_data=run_data, band=band, seed=seed,
        flags=report.flagged, invariants=inv, control=ctl,
        derived_dir=paths.root, manifests_dir=paths.manifests,
        provenance={
            "source": "synthetic",
            "generator": "pipeline.model.stream, exponential-covariance Gaussian process in cumulative "
            "tonnage",
            "license": "CC-BY-4.0, generated by this repository",
            "contract": report.summary(),
        },
    )
    return manifest, evaluate.matrix_row(case, run_data, band)


def run_all(seed: int = 42, *, output_root: str | Path | None = None,
            band_seeds: int = BAND_SEEDS) -> dict:
    """Bake every registered case, write the index, and run the release gate."""
    paths = PipelinePaths.from_output(output_root)
    entries: list[dict] = []
    rows: dict[str, dict] = {}

    for case in registry.list_cases():
        man, row = precompute(case.id, seed=seed, output_root=paths.root, band_seeds=band_seeds)
        entries.append({"case_id": case.id, "category": case.category,
                        "manifest_path": f"manifests/{case.id}.json"})
        rows[case.id] = row
        print(f"  baked {case.id:22s} lane={man['lane']:11s} "
              f"vrr={man['metrics']['vrr']:.4f} bytes={man['artifact']['bytes']}", flush=True)

    write_json(paths.manifests / "index.json", build_index(entries))
    write_json(paths.root / "matrix.json", {
        "rows": list(rows.values()),
        "assertions": evaluate.benchmark_assertions(rows),
        "anchors": evaluate.PUBLISHED_ANCHORS,
    })
    return validate.run(paths.root, paths.manifests, [c.id for c in registry.list_cases()])


def main() -> None:
    ap = argparse.ArgumentParser(prog="pipeline.pipeline")
    ap.add_argument("case", nargs="?", default="all", help="a case id, or 'all'")
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--band-seeds", type=int, default=BAND_SEEDS,
                    help="seeds per multi-seed band; lower only for a smoke run")
    ap.add_argument("--output", type=Path,
                    help="sandbox output root; omit only for an intentional canonical release bake")
    ap.add_argument("--validate-only", action="store_true",
                    help="run the release gate over an already-baked tree and exit")
    args = ap.parse_args()
    paths = PipelinePaths.from_output(args.output)

    if args.validate_only:
        rep = validate.run(paths.root, paths.manifests, [c.id for c in registry.list_cases()])
        _print_report(rep)
        sys.exit(0 if rep["ok"] else 1)

    if args.case == "all":
        rep = run_all(args.seed, output_root=args.output, band_seeds=args.band_seeds)
        _print_report(rep)
        sys.exit(0 if rep["ok"] else 1)

    man, _row = precompute(args.case, args.seed, output_root=args.output, band_seeds=args.band_seeds)
    print(f"baked {args.case}: lane={man['lane']} bytes={man['artifact']['bytes']} "
          f"vrr={man['metrics']['vrr']:.4f} -> {paths.root / man['artifact']['path']}")


def _print_report(rep: dict) -> None:
    print(f"\nvalidate: {rep['cases_checked']}/{rep['cases_expected']} cases, lanes {rep['lanes']}")
    if rep["ok"]:
        print("validate: OK")
        return
    print(f"validate: failed with {len(rep['problems'])} problems")
    for p in rep["problems"]:
        print(f"  - {p}")


if __name__ == "__main__":
    main()
