"""The CONTROLLED lane: sequential Gaussian simulation with a DECLARED variogram.

WHY THIS EXISTS, given that the live lane already produces a correlated stream. The live lane's
exponential recursion is exact for the exponential model and for nothing else. Two of the four claims
this product makes about blending depend on the variogram of the input: that the layers a cut crosses
stop being independent once the range exceeds one layer's tonnage, and that the app can RECOVER the
input structure from the reclaimed stream. Testing a recovery routine against a stream generated by
the same closed form it assumes is circular. This lane breaks the circle: GSTools generates the field
by its own spectral method, over Gaussian, exponential, Matern and stable models, and the app's fit is
then scored against a range and sill it was never told.

THE RANGE CONVENTION, which is the easy way to be wrong here. This product states variogram ranges as
the PRACTICAL range: the lag at which the model reaches 95 percent of its sill. GSTools parameterises
by `len_scale`. For the exponential model gamma(h) = s (1 - exp(-h/l)), so the practical range is
a = 3 l; for the Gaussian model it is a = sqrt(3) l. Passing a practical range straight in as
`len_scale` would produce a field whose true range is three times what every label says, and every
recovery test would then pass against the wrong truth. `_len_scale` does the conversion explicitly
and the round-trip test asserts it.

Muller, Schuler, Zech and Hesse, "GSTools v1.3: a toolbox for geostatistical modelling in Python",
Geosci. Model Dev. 15, 3161-3182 (2022), doi:10.5194/gmd-15-3161-2022. BSD-3-Clause.
"""
from __future__ import annotations

import math
from dataclasses import dataclass

import numpy as np
from bedblend.schema import TruckDump

#: model name -> (GSTools class name, practical range / len_scale)
MODELS: dict[str, tuple[str, float]] = {
    "exponential": ("Exponential", 3.0),
    "gaussian": ("Gaussian", math.sqrt(3.0)),
    "matern": ("Matern", 3.0),          # nu = 1 by default; the 3.0 is the exponential-limit value
    "stable": ("Stable", 3.0),          # alpha = 1.5 by default
}

MODEL_NOTES: dict[str, dict[str, str]] = {
    "exponential": {
        "en": "The standard mining model. Rough at the origin, so consecutive trucks differ even at "
              "very short lag, which is what a real dispatch record looks like.",
        "es": "El modelo estandar en mineria. Aspero en el origen, de modo que camiones consecutivos "
              "difieren incluso a lag muy corto, que es como se ve un registro real de despacho.",
    },
    "gaussian": {
        "en": "Smooth at the origin: consecutive trucks are nearly identical and the difference only "
              "appears at longer lag. This is the case where a bed looks best and the case where "
              "assuming an exponential fit misreads the range most badly.",
        "es": "Suave en el origen: camiones consecutivos son casi identicos y la diferencia solo "
              "aparece a lag mayor. Es el caso donde la cama se ve mejor y donde suponer un ajuste "
              "exponencial peor estima el alcance.",
    },
    "matern": {
        "en": "The family the other two are limits of, with smoothness as a free parameter. Included "
              "so the recovery test is not tuned to two special cases.",
        "es": "La familia de la que los otros dos son límites, con la suavidad como parámetro libre. "
              "Incluido para que la prueba de recuperación no quede ajustada a dos casos especiales.",
    },
    "stable": {
        "en": "Between the exponential and the Gaussian at the origin. The honest default when the "
              "short-lag behaviour of a real record is unknown.",
        "es": "Entre el exponencial y el gaussiano en el origen. El valor razonable cuando el "
              "comportamiento a lag corto de un registro real se desconoce.",
    },
}


@dataclass(frozen=True)
class ControlledLaneSpec:
    model: str = "exponential"
    range_t: float = 4000.0            # t, PRACTICAL range (95 percent of sill)
    sill: float = 0.0256               # (percent Cu)^2, that is sd 0.16
    mean_cu: float = 0.62
    nugget: float = 0.0
    tonnes_per_truck: float = 220.0
    truck_spread: float = 0.06
    cycle_s: float = 90.0
    coarse_mean: float = 0.35
    coarse_sd: float = 0.08


def _require():
    try:
        import gstools  # noqa: F401
    except ModuleNotFoundError as exc:  # pragma: no cover - exercised by the offline-lane CI job
        raise ModuleNotFoundError(
            "the controlled lane needs the GSTools engine: pip install -r requirements-offline.txt"
        ) from exc
    return gstools


def _len_scale(model: str, range_t: float) -> float:
    """Practical range to GSTools len_scale. See the module docstring: this is the trap."""
    if model not in MODELS:
        raise ValueError(f"unknown variogram model {model!r}; expected one of {sorted(MODELS)}")
    return range_t / MODELS[model][1]


def build_model(spec: ControlledLaneSpec):
    gs = _require()
    cls = getattr(gs, MODELS[spec.model][0])
    return cls(dim=1, var=spec.sill, len_scale=_len_scale(spec.model, spec.range_t),
               nugget=spec.nugget)


def controlled_truck_log(n_dumps: int, seed: int,
                         spec: ControlledLaneSpec | None = None) -> list[TruckDump]:
    """Emit ``n_dumps`` truck loads from an SGS field over the cumulative-tonnage axis.

    The field is simulated on the tonnage axis, not the truck-index axis. Trucks are not all the same
    size, so a field over the index would put the declared range at the wrong place in tonnes, and
    tonnes are the units every claim in this product is stated in.
    """
    spec = spec or ControlledLaneSpec()
    gs = _require()
    rng = np.random.default_rng((seed * 6364136223846793005 + 1442695040888963407) & 0xFFFFFFFF)

    t_t = np.maximum(20.0, spec.tonnes_per_truck * (1.0 + spec.truck_spread * rng.normal(size=n_dumps)))
    cum = np.cumsum(t_t) - 0.5 * t_t          # sample at each load's tonnage midpoint

    srf = gs.SRF(build_model(spec), mean=spec.mean_cu, seed=seed)
    cu = np.maximum(0.0, np.asarray(srf.unstructured([cum]), dtype=np.float64))

    # size is an independent field: block-model grade says nothing about crusher product size, and
    # coupling them would bake in a correlation no dataset here supports
    size_srf = gs.SRF(build_model(spec), mean=0.0, seed=(seed ^ 0x5BF03635) & 0x7FFFFFFF)
    zs = np.asarray(size_srf.unstructured([cum]), dtype=np.float64)
    zs = zs / max(1e-12, float(np.std(zs)))
    coarse = np.clip(spec.coarse_mean + spec.coarse_sd * zs, 0.05, 0.95)

    return [
        TruckDump(
            event_id=k,
            t_s=k * spec.cycle_s,
            truck_id=f"T{(k % 12) + 1:02d}",
            source_id=f"SGS-{spec.model[:3].upper()}",
            tonnes=float(t_t[k]),
            grade_cu_pct=float(cu[k]),
            grade_au_gpt=max(0.0, 0.12 + 0.05 * float(rng.normal())),
            coarse_frac=float(coarse[k]),
            moisture_pct=3.0,
            x_m=0.0,
            y_m=0.0,
        )
        for k in range(n_dumps)
    ]


def lane_provenance(spec: ControlledLaneSpec, seed: int) -> dict:
    note = MODEL_NOTES.get(spec.model, {"en": "", "es": ""})
    return {
        "lane": "controlled",
        "engine": "gstools",
        "engine_doi": "10.5194/gmd-15-3161-2022",
        "licence": "BSD-3-Clause",
        "variogram_model": spec.model,
        "declared_range_t": spec.range_t,
        "declared_sill": spec.sill,
        "len_scale": _len_scale(spec.model, spec.range_t),
        "range_convention": "practical range, the lag at 95 percent of the sill",
        "seed": seed,
        "synthetic": True,
        "coarse_fraction_is_synthetic": True,
        "note_en": note["en"],
        "note_es": note["es"],
    }
