// ADR-0058: the in-app Architecture modal. Five tabs, each pairing ONE hand-authored theme-aware SVG
// with a bilingual explanation, opened by the always-visible header button.
//
// The SVGs live in public/svg/tech/ and are FETCHED AND INLINED by the shell, which is why every
// colour in them is a CSS variable token: an <img> would not inherit the variables and a single
// hardcoded hex would break one theme.
//
// The depth here is meant to be complete rather than a teaser. A reader who opens the modal and reads
// every tab should come away knowing the system as well as reading the repository wiki.
//
// BOTH LANGUAGES SAY THE SAME THING. They drifted once: the English had been rewritten for the
// truck-built product while the Spanish still described five conveyor stacking geometries, Pyodide
// and seventeen cases, none of which exist. A Spanish reader was being told about a different piece
// of software. Any edit here changes the pair.

import type { ArchitectureConfig } from '@fasl-work/caos-app-shell';

export const architecture: ArchitectureConfig = {
  title_en: 'How StockTwin works',
  title_es: 'Cómo funciona StockTwin',
  tabs: [
    {
      id: 'app',
      en: 'The app',
      es: 'La aplicación',
      svg: 'svg/tech/01-the-app.svg',
      body_en:
        'StockTwin builds a run-of-mine stockpile the way one is actually built: by trucks, one load at a time, following a dump plan. A truck routes over ground it can climb, spots against the working face, tips, and leaves. The material stands at its angle of repose, a dozer turns the tipped heaps into a floor, and the next lift starts higher than the last. A stockpile is a planned earthwork, and this is the inverse of an open pit: benches going up instead of down, with the same primitives of working level, face, berm and ramp.\n\n'
        + 'It answers three questions. How much does the pile homogenize the feed, measured as the variance reduction ratio and always shown against the independent-layer bound. Where did this reclaimed tonne come from, answered by the per-cell lot ledger. And how much is size segregation biasing the cut, answered by a published continuum model solved down a real face rather than by a rule of thumb.\n\n'
        + 'THE TRUCK IS THE SUBJECT, not a delivery mechanism. It has a route in and a route out, it refuses a tip it cannot reach, and where it can reach changes as the pile grows. Fresh material stands at about 37 degrees and a haul truck climbs about two thirds of that, so a truck never stands on fresh material. That single fact is why the plan, the ramp and the dozer exist at all rather than being decoration.\n\n'
        + 'The design-build flow behind it: a deep research pass persisted as dated dossiers, a plan validated before any code, then unit by unit the engine, its invariant tests and its documentation page in the same commit. Nothing in the docs is recalled from memory; it is transcribed from the dossiers at build time.\n\n'
        + 'What it is not: in-plant metal accounting, a comminution or flotation model, or a blending optimizer. It exposes the state an optimizer would consume and emits no plant setpoint.',
      body_es:
        'StockTwin construye un acopio ROM como se construye realmente: con camiones, carga por carga, siguiendo un plan de descarga. Un camion se enruta sobre terreno que puede subir, se ubica contra la cara de trabajo, descarga y se retira. El material queda en su angulo de reposo, un bulldozer convierte los montones en piso, y el banco siguiente parte mas arriba que el anterior. Un acopio es una obra de tierra planificada, y esto es el inverso de un rajo abierto: bancos que suben en vez de bajar, con las mismas primitivas de nivel de trabajo, cara, berma y rampa.\n\n'
        + 'Responde tres preguntas. Cuanto homogeniza la pila la alimentacion, medido como razon de reduccion de varianza y siempre mostrado contra la cota de capas independientes. De donde vino esta tonelada recuperada, que responde el libro mayor de lotes por celda. Y cuanto sesga la segregacion por tamano lo que contiene el corte, que responde un modelo continuo publicado resuelto sobre una cara real y no una regla practica.\n\n'
        + 'EL CAMION ES EL SUJETO, no un mecanismo de entrega. Tiene una ruta de llegada y una de salida, rechaza un punto de descarga que no puede alcanzar, y lo que puede alcanzar cambia a medida que la pila crece. El material fresco se para cerca de 37 grados y un camion de extraccion sube alrededor de dos tercios de eso, asi que un camion nunca se para sobre material fresco. Ese solo hecho es la razon de que existan el plan, la rampa y el bulldozer, en vez de ser decoracion.\n\n'
        + 'El flujo de diseno detras: una pasada profunda de investigacion persistida en dosieres fechados, un plan validado antes de escribir codigo, y luego unidad por unidad el motor, sus pruebas de invariantes y su pagina de documentacion en el mismo commit. Nada en la documentacion se escribe de memoria: se transcribe de los dosieres al construir.\n\n'
        + 'Lo que NO es: contabilidad metalurgica de planta, un modelo de conminucion o flotacion, ni un optimizador de mezcla. Expone el estado que consumiria un optimizador y no emite ninguna consigna de planta.',
    },
    {
      id: 'lanes',
      en: 'The lanes',
      es: 'Los carriles',
      svg: 'svg/tech/02-lanes.svg',
      body_en:
        'Three lanes with separate dependencies and separate implementations.\n\n'
        + 'LIVE, in the browser, TypeScript: the VERDICTS, recomputed from the event log on every load. Variance reduction, the independent-layer bound, the variograms, the sector rollups with their confidence intervals and the segregation summary are all derived in the page from the loads and cuts it also displays. The SIMULATION is not live, and that is deliberate: it routes every load over the trafficable surface with an A-star search, floods the pad for reachability and relaxes the whole height field after every operation, which is tens of seconds for a few hundred loads. Running that in a page means either a frozen tab or a model simple enough to be wrong, and the previous version of this product chose the second.\n\n'
        + 'OFFLINE, precompute, Python: the canonical bake, on the published `bedblend` engine. Terrain, the dump plan, the two construction phases, every routed load with its approach and departure, the dozer passes, the face segregation solve, the reclaim cuts, and one surface snapshot per placed load. The bake gates on the artifact it produced, not on the code that produced it.\n\n'
        + 'REPLAY: the committed compact trace plus its manifest. First paint, the playback, and whatever the live lane cannot do. Snapshots are stored at a coarse cell stride and interpolated back onto the full grid in the browser, which is what makes one frame per truck affordable instead of one frame per twenty.\n\n'
        + 'The lane is decided by measurement, not by intent: the gate records the measured runtime and byte size and writes the verdict into the manifest.',
      body_es:
        'Tres carriles con dependencias e implementaciones separadas.\n\n'
        + 'EN VIVO, en el navegador, TypeScript: los VEREDICTOS, recalculados desde el registro de eventos en cada carga. La reduccion de varianza, la cota de capas independientes, los variogramas, los resumenes por sector con sus intervalos de confianza y el resumen de segregacion se derivan en la pagina a partir de las mismas cargas y cortes que muestra. La SIMULACION no es en vivo, y eso es deliberado: enruta cada carga sobre la superficie transitable con una busqueda A-estrella, inunda la losa para calcular alcanzabilidad y relaja todo el campo de alturas despues de cada operacion, lo que toma decenas de segundos para unos cientos de cargas. Correr eso en una pagina significa una pestana congelada o un modelo lo bastante simple como para estar equivocado, y la version anterior de este producto eligio lo segundo.\n\n'
        + 'FUERA DE LINEA, precomputo, Python: el horneado canonico, sobre el motor publicado `bedblend`. El terreno, el plan de descarga, las dos fases de construccion, cada carga enrutada con su llegada y su salida, las pasadas del bulldozer, la resolucion de segregacion en la cara, los cortes de recuperacion, y una instantanea de superficie por carga colocada. El horneado se evalua contra el artefacto que produjo, no contra el codigo que lo produjo.\n\n'
        + 'REPLAY: la traza compacta comprometida mas su manifiesto. El primer dibujo, la reproduccion, y todo lo que el carril en vivo no pueda hacer. Las instantaneas se guardan con un paso de celda grueso y se interpolan de vuelta a la grilla completa en el navegador, que es lo que hace asequible un cuadro por camion en vez de uno cada veinte.\n\n'
        + 'El carril se decide por medicion, no por intencion: la compuerta registra el tiempo y el tamano medidos y escribe el veredicto en el manifiesto.',
    },
    {
      id: 'web',
      en: 'The web app',
      es: 'La aplicación web',
      svg: 'svg/tech/03-web-flow.svg',
      body_en:
        'A static single-page application with no backend. The App route is a workbench over one scenario at a time; the five documentation routes are prose; the focus route renders outside the shell because the header and footer are exactly the chrome it exists to escape.\n\n'
        + 'The App is built from the shared shell primitives rather than from local copies of them: the case selector, the tab strip, the callouts, the equations and the citations all come from the shell. An earlier version hand-rolled every one of those plus a full-bleed width hack, which is how the footer ended up under the tab bar.\n\n'
        + 'The build has three separate steps that never merge. The canonical bake writes the traces and manifests into data/derived and is an explicit release operation. The web build copies those already-audited artifacts into the site and compiles the bundle; a TypeScript mirror of the artifact schema means a drift between the Python writer and the browser reader fails the build. Deployment verifies the committed artifacts and publishes; a deployment is never an experiment.\n\n'
        + 'Every verdict the page shows is recomputed in the browser from the trace events. The trace deliberately carries no baked variance reduction ratio, so a reader can switch scenario, watch the number move, and know it was derived rather than looked up.',
      body_es:
        'Una aplicacion de pagina unica estatica, sin backend. La ruta App es un banco de trabajo sobre un escenario a la vez; las cinco rutas de documentacion son prosa; la ruta de foco se dibuja fuera del shell porque el encabezado y el pie son exactamente el cromo del que existe para escapar.\n\n'
        + 'La App se construye con las primitivas del shell compartido y no con copias locales: el selector de casos, la barra de pestanas, los avisos, las ecuaciones y las citas vienen todos del shell. Una version anterior escribia a mano cada una de ellas mas un truco de ancho completo, que es como el pie termino debajo de la barra de pestanas.\n\n'
        + 'La construccion tiene tres pasos separados que nunca se mezclan. El horneado canonico escribe las trazas y manifiestos en data/derived y es una operacion explicita de release. La construccion web copia esos artefactos ya auditados al sitio y compila el paquete; un espejo TypeScript del esquema del artefacto hace que una divergencia entre el escritor Python y el lector del navegador rompa la construccion. El despliegue verifica los artefactos comprometidos y publica; un despliegue nunca es un experimento.\n\n'
        + 'Cada veredicto que muestra la pagina se recalcula en el navegador a partir de los eventos de la traza. La traza deliberadamente no lleva una razon de reduccion de varianza horneada, de modo que un lector puede cambiar de escenario, ver moverse el numero y saber que fue derivado y no consultado.',
    },
    {
      id: 'science',
      en: 'The science',
      es: 'La ciencia',
      svg: 'svg/tech/04-the-science.svg',
      body_en:
        'Dig sequence to truck stream to planned earthwork to reclaim cut, with the equations at each step.\n\n'
        + 'the stream. A stationary Gaussian process in cumulative tonnage with an exponential covariance, C(h) = sill exp(-3h/a), generated exactly by a one-step recursion. The autocorrelation is not a knob: it EMERGES from shovel dwell, the number of loads a shovel takes from one dig block before it moves. If consecutive trucks are correlated, the layers a cut crosses are not independent samples, and a white-noise input would make every bed look excellent while hiding the dominant effect in the domain.\n\n'
        + 'the earthwork. The plan divides the yard into areas with an access point and a ramp, and each area into benches. Phase one lays paddock dumps, elliptical frustums sized by the truck body, standing initially near 2:1 and settling to repose. The dozer levels them into a floor. Phase two advances a crest in radial sweeps, each edge dump run perpendicular to the crest tangent, until the designed bench volume is filled.\n\n'
        + 'the dump. Four measured profiles, oval, comet, rectangular and sloughed heap, selected by distance to the crest, and calibrated to a published envelope: length 13 to 46 m, width 11 to 23 m, thickness 0.368 to 2.032 m, angle 12 to 36 degrees, volume 94 to 155 cubic metres.\n\n'
        + 'the pile. A height field relaxes until no local slope exceeds the imposed angle of repose, over the ORIGINAL GROUND as a floor so relaxation can never erode bedrock. A cell topples exactly to its repose surface in one step by giving away t_k = max(0, d_k - T) with T solving T = sum_k max(0, d_k - T). The highest unstable cell topples first, so the ordered transfers are the avalanche path. A cell that gives material away destabilises the cells ABOVE it, which is the correction that removed 446 spikes standing at 55.9 degrees against an imposed 37.\n\n'
        + 'the segregation. Gray and Thornton (2005) equation (3.20): on a flank, plug flow reduces the model to a one-dimensional conservation law in depth, dphi/dx + d/dz[-Sr phi(1-phi)] = 0, with no flux at the surface or the base, solved with a Godunov flux so the concentration shocks survive. It is solved down a REAL face taken from the terrain, not down a nominal slope, so a load that never ran out on a face is not sorted at all.\n\n'
        + 'the value. VRR = var_out / var_in on a tonnage base, lower is better, always against the derived bound 1/N. Real beds recover roughly a quarter to a third of that ideal, and the product shows the gap rather than the flattering half of it. Where the effective layer count cannot be estimated reliably the bound is WITHHELD rather than shown wrong.',
      body_es:
        'Secuencia de extraccion a flujo de camiones a obra de tierra planificada a corte recuperado, con las ecuaciones en cada paso.\n\n'
        + 'EL FLUJO. Un proceso gaussiano estacionario en tonelaje acumulado con covarianza exponencial, C(h) = meseta exp(-3h/a), generado exactamente por una recursion de un paso. La autocorrelacion no es una perilla: EMERGE de la permanencia de la pala, el numero de cargas que una pala toma de un bloque antes de moverse. Si camiones consecutivos estan correlacionados, las capas que cruza un corte no son muestras independientes, y una entrada de ruido blanco haria que toda cama pareciera excelente ocultando el efecto dominante del dominio.\n\n'
        + 'LA OBRA DE TIERRA. El plan divide el patio en areas con un punto de acceso y una rampa, y cada area en bancos. La fase uno coloca descargas de paddock, troncos elipticos dimensionados por la tolva del camion, que se paran cerca de 2:1 y se asientan al reposo. El bulldozer los nivela en un piso. La fase dos avanza una cresta en barridos radiales, cada descarga de borde perpendicular a la tangente de la cresta, hasta llenar el volumen de banco disenado.\n\n'
        + 'LA DESCARGA. Cuatro perfiles medidos, ovalo, cometa, rectangular y monton desmoronado, elegidos por la distancia a la cresta y calibrados a una envolvente publicada: largo 13 a 46 m, ancho 11 a 23 m, espesor 0,368 a 2,032 m, angulo 12 a 36 grados, volumen 94 a 155 metros cubicos.\n\n'
        + 'LA PILA. Un campo de alturas se relaja hasta que ninguna pendiente local supera el angulo de reposo impuesto, con el TERRENO ORIGINAL como piso para que la relajacion nunca pueda erosionar la roca. Una celda cae exactamente a su superficie de reposo en un paso cediendo t_k = max(0, d_k - T) con T que resuelve T = suma_k max(0, d_k - T). La celda inestable mas alta cae primero, de modo que las transferencias ordenadas son el camino de la avalancha. Una celda que cede material desestabiliza las celdas de ARRIBA, que es la correccion que elimino 446 espigas paradas a 55,9 grados contra un reposo impuesto de 37.\n\n'
        + 'LA SEGREGACION. Ecuacion (3.20) de Gray y Thornton (2005): en un flanco, el flujo tapon reduce el modelo a una ley de conservacion unidimensional en profundidad, dphi/dx + d/dz[-Sr phi(1-phi)] = 0, sin flujo en la superficie ni en la base, resuelta con un flujo de Godunov para que sobrevivan los choques de concentracion. Se resuelve sobre una CARA REAL tomada del terreno, no sobre una pendiente nominal, asi que una carga que nunca corrio sobre una cara no queda clasificada.\n\n'
        + 'EL VALOR. VRR = var_salida / var_entrada sobre base de tonelaje, menor es mejor, siempre contra la cota derivada 1/N. Las camas reales recuperan aproximadamente entre un cuarto y un tercio de ese ideal, y el producto muestra la brecha en vez de solo la mitad halagadora. Cuando el numero efectivo de capas no puede estimarse de forma confiable, la cota se OMITE en vez de mostrarse mal.',
    },
    {
      id: 'contracts',
      en: 'The data contracts',
      es: 'Los contratos de datos',
      svg: 'svg/tech/05-data-contracts.svg',
      body_en:
        'contract 1, ingestion: the bring-your-own-data gate, written against the fleet-management dump record a mine already has. Timestamp, grade identifier, assay, the name and bench height of the dump location polygon, easting and northing, tonnage. A row failing a hard range is rejected with a stated reason; a row failing a soft check is flagged, kept, counted and rendered with a marker; nothing is silently coerced, because a coerced row looks like data and is not. Rows out of time order and dumps outside the pad extent are rejected.\n\n'
        + 'contract 2, artifact: the manifest and the compact trace. The manifest is a pure function of parameters and seed, with no wall-clock and no absolute path, so a re-bake that changes nothing changes no bytes and the git history of the evidence stays readable. It carries the scenario and why it is in the matrix, the build statistics, the profile census, the material properties, and the gate results.\n\n'
        + 'the scenarios are the validation design. TWENTY-TWO of them, across six axes: a reference stock for reading the physics; four feed-structure cases that change ONLY how long the shovel dwells in one dig block, to show the blending result follows the dig sequence rather than the ore; three yard cases covering routing and misrouting by ore-control class; four landform cases, because only one of the five published stockpile fill types is a flat pad; six campaign cases covering intensive feeding, intensive and light draining, a two-phase build, and two where the loader draws the pile down WHILE trucks are still tipping into it; and four operating-choice cases for bench height, ramp width, dozer cadence and wet material. Each states its reason for inclusion and a kill criterion, and the bake gate enforces them on the ACTUAL artifact: zero cell pairs over the angle of repose, the ledger agreeing with the terrain column by column, mass conserved to one part in a million, and no cell below its original ground. TWO further cases were withdrawn for failing their own criterion, a steep sidehill leaving 22 pairs at 45.9 degrees and a ridge crest leaving one at 41.5, rather than have the tolerance widened to fit them.\n\n'
        + 'the refusals are part of the record. 19.2 percent of the planned tips on the reference case are refused because the truck cannot reach them, and that number is reported rather than hidden. The plan is generated once while the pile grows away from it; a real operation re-plans, and saying so is more useful than quietly moving the truck to somewhere it could not have driven.',
      body_es:
        'contrato 1, ingesta: la puerta de trae-tus-propios-datos, escrita contra el registro de descargas que un sistema de gestion de flota ya produce. Marca de tiempo, identificador de ley, ensayo, nombre y cota de banco del poligono de descarga, este y norte, tonelaje. Una fila que falla un rango duro se rechaza con una razon declarada; una que falla una verificacion blanda se marca, se conserva, se cuenta y se dibuja con un indicador; nada se corrige en silencio, porque una fila corregida parece dato y no lo es. Se rechazan las filas fuera de orden temporal y las descargas fuera de la losa.\n\n'
        + 'contrato 2, artefacto: el manifiesto y la traza compacta. El manifiesto es funcion pura de parametros y semilla, sin reloj ni rutas absolutas, de modo que un rehorneado que no cambia nada no cambia ningun byte y la historia de la evidencia sigue siendo legible. Lleva el escenario y por que esta en la matriz, las estadisticas de construccion, el censo de perfiles, las propiedades del material y los resultados de la compuerta.\n\n'
        + 'LOS ESCENARIOS SON EL DISENO DE VALIDACION. VEINTIDOS, en seis ejes: un acopio de referencia para leer la fisica; cuatro casos de estructura de alimentacion que cambian SOLO cuanto permanece la pala en un bloque, para mostrar que el resultado de mezcla sigue a la secuencia de extraccion y no al mineral; tres casos de patio que cubren ruteo y ruteo erroneo por clase de control de leyes; cuatro casos de relieve, porque solo uno de los cinco tipos publicados de relleno de acopio es una losa plana; seis casos de campana que cubren alimentacion intensiva, drenaje intensivo y liviano, una construccion en dos fases, y dos donde el cargador baja la pila MIENTRAS los camiones siguen descargando en ella; y cuatro casos de decisiones operativas para altura de banco, ancho de rampa, cadencia del bulldozer y material humedo. Cada uno declara su razon de inclusion y un criterio de descarte, y la compuerta del horneado los aplica sobre el ARTEFACTO REAL: cero pares de celdas sobre el angulo de reposo, el libro mayor coincidiendo con el terreno columna por columna, masa conservada a una parte en un millon, y ninguna celda bajo su terreno original. DOS casos mas fueron retirados por fallar su propio criterio, una ladera empinada que dejaba 22 pares a 45,9 grados y una cresta que dejaba uno a 41,5, en vez de ensanchar la tolerancia para que cupieran.\n\n'
        + 'LOS RECHAZOS SON PARTE DEL REGISTRO. El 19,2 por ciento de los puntos de descarga planificados en el caso de referencia se rechazan porque el camion no puede alcanzarlos, y ese numero se reporta en vez de esconderse. El plan se genera una vez mientras la pila crece alejandose de el; una operacion real replanifica, y decirlo es mas util que mover el camion en silencio a un lugar al que no pudo haber llegado.',
    },
  ],
};
