#!/usr/bin/env python3
"""Emit the case registry as TypeScript, so the two lanes cannot disagree about what a case IS.

The case matrix is the product's validation design (ADR-0069 clause 4). Hand-mirroring seventeen cases
with their reasons, expected bands, kill criteria and parameters into a second language would drift on
the first edit, and the drift would be invisible: the app would simply be running a slightly different
experiment from the one the pipeline baked and the Benchmark page reported.

So the Python registry is the single source and this script generates the TypeScript. CI re-runs it and
fails if the working tree changes, which turns "someone edited one side only" into a build failure
instead of a discrepancy nobody notices.

    python scripts/export_cases.py            # write the file
    python scripts/export_cases.py --check    # exit 1 if it would change
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "data-pipeline"))

from pipeline.cases.definitions import CASES, CATEGORIES  # noqa: E402

OUT = ROOT / "frontend" / "src" / "engine" / "cases.generated.ts"

HEADER = """// GENERATED by scripts/export_cases.py from data-pipeline/stlab/cases/definitions.py. Do not edit.
//
// The Python registry is the single source for the case matrix. CI re-runs the generator and fails if
// this file would change, so the browser and the offline bake can never be running different
// experiments while both reporting the same case ids.
//
// Every field is the one ADR-0069 clause 4 requires of a case: its category, the scientific reason it
// is in the matrix, its expected behaviour, the kill criterion that says what result would mean the
// code is wrong, and its split assignment.

import type { ReclaimMethod, StackingMethod, StreamStructure } from './types';

export interface CaseDef {
  id: string;
  category: string;
  reason: string;
  expectedBand: string;
  killCriterion: string;
  realOrSynthetic: string;
  split: string;
  stacking: StackingMethod;
  reclaim: ReclaimMethod;
  nPasses: number;
  reclaimRate: number;
  cutTonnes: number;
  startFraction: number;
  sr: number;
  reposeDeg: number;
  reposeCoarseDeg: number;
  structure: StreamStructure;
  rangeT: number;
  nDumps: number;
  coarseSd: number;
  nx: number;
  ny: number;
  cellM: number;
  tags: string[];
}

export const CATEGORY_LABELS: Record<string, string> = %CATS%;

export const CASES: CaseDef[] = %CASES%;

export const CASES_BY_ID: Record<string, CaseDef> = Object.fromEntries(CASES.map((c) => [c.id, c]));

export function casesByCategory(): Array<{ category: string; label: string; cases: CaseDef[] }> {
  const order = Object.keys(CATEGORY_LABELS);
  return order.map((category) => ({
    category,
    label: CATEGORY_LABELS[category],
    cases: CASES.filter((c) => c.category === category),
  })).filter((g) => g.cases.length > 0);
}
"""


def build() -> str:
    rows = []
    for c in CASES:
        rows.append({
            "id": c.id, "category": c.category, "reason": c.reason,
            "expectedBand": c.expected_band, "killCriterion": c.kill_criterion,
            "realOrSynthetic": c.real_or_synthetic, "split": c.split,
            "stacking": c.stacking, "reclaim": c.reclaim, "nPasses": c.n_passes,
            "reclaimRate": c.reclaim_rate, "cutTonnes": c.cut_tonnes,
            "startFraction": c.start_fraction, "sr": c.sr, "reposeDeg": c.repose_deg,
            "reposeCoarseDeg": c.repose_coarse_deg, "structure": c.structure,
            "rangeT": c.range_t, "nDumps": c.n_dumps, "coarseSd": c.coarse_sd,
            "nx": c.nx, "ny": c.ny, "cellM": c.cell_m, "tags": list(c.tags),
        })
    return (HEADER
            .replace("%CATS%", json.dumps(CATEGORIES, indent=2, ensure_ascii=False))
            .replace("%CASES%", json.dumps(rows, indent=2, ensure_ascii=False)))


def main() -> None:
    ap = argparse.ArgumentParser(prog="export_cases")
    ap.add_argument("--check", action="store_true", help="exit 1 if the generated file is stale")
    args = ap.parse_args()
    text = build()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"STALE: {OUT.relative_to(ROOT)} does not match the Python case registry.")
            print("Run: python scripts/export_cases.py")
            sys.exit(1)
        print(f"OK: {OUT.relative_to(ROOT)} matches the Python case registry ({len(CASES)} cases).")
        return
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(CASES)} cases)")


if __name__ == "__main__":
    main()
