#!/usr/bin/env python3
"""Generate the parts of the docs wiki that are DERIVED from the code, so they cannot drift.

Three things in the wiki are restatements of what the code already declares: the case pages, the case
taxonomy and coverage matrix, and the ingestion contract table. Writing them by hand guarantees that
the first edit to a kill criterion or a validation range leaves the documentation quietly wrong, and
quietly wrong documentation is worse than none, because a reader trusts it.

Everything else in `docs/` is authored prose and lives in git, not here.

    python scripts/gen_docs.py
    python scripts/gen_docs.py --check     # exit 1 if any generated page is stale
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "data-pipeline"))

from bedblend.pile import RECLAIM_GEOMETRY  # noqa: E402
from pipeline.cases.definitions import CASES, CATEGORIES, variants_for  # noqa: E402
from pipeline.io.contract import contract_doc  # noqa: E402

DOCS = ROOT / "docs"
BANNER = "<!-- GENERATED by scripts/gen_docs.py. Do not edit; edit the code it reads. -->\n\n"


def _variant_table(c) -> str:
    """The case's regimes, or the honest statement that it has none."""
    vs = variants_for(c)
    if not vs:
        return (
            "This case carries **no variants**, and that is deliberate. It is a control: one point "
            "with a numerical kill criterion. Sweeping it would destroy the property that makes it a "
            "control, and padding the list to reach a count would be fabricating regimes."
        )
    knob = next(iter(vs[0].overrides))
    lines = [
        f"The family sweeps `{knob}`, the parameter this case's category actually turns on. Selecting",
        "a regime in the app re-runs the engine in the browser rather than loading a pre-baked frame,",
        "so the sweep is continuous with the rail's own controls.",
        "",
        f"| regime | `{knob}` | what it shows |",
        "|---|---|---|",
    ]
    for v in vs:
        lines.append(f"| {v.label_en} | `{v.overrides[knob]}` | {v.note_en} |")
    return "\n".join(lines)


def case_page(c) -> str:
    return BANNER + f"""# Case `{c.id}`

**Category:** {c.category} ({CATEGORIES[c.category]})
**Source:** {c.real_or_synthetic} · **Split:** {c.split}

## Why it is in the matrix

{c.reason}

## Expected behaviour

{c.expected_band}

## Kill criterion

> {c.kill_criterion}

This is the statement that turns the case from a demonstration into a test. It says, in advance, what
result would mean the code is wrong, and the release gate fails the bake when it is violated.

## Configuration

| parameter | value | what it controls |
|---|---|---|
| `stacking` | `{c.stacking}` | the deposition path over the pad |
| `reclaim` | `{c.reclaim}` | which cells the machine engages and how deep it reaches |
| `n_passes` | {c.n_passes} | stacker passes, that is layers: the N of the 1/N bound |
| `sr` | {c.sr} | the Gray-Thornton segregation number; 0 is a passive tracer |
| `repose_deg` | {c.repose_deg} | the imposed angle of repose of the fine species |
| `repose_coarse_deg` | {c.repose_coarse_deg} | the coarse species; a positive difference is Makse |
| `structure` | `{c.structure}` | the autocorrelation structure of the incoming stream |
| `range_t` | {c.range_t:.0f} t | the practical range of the input variogram, in tonnes |
| `n_dumps` | {c.n_dumps} | truck loads in the build |
| `reclaim_rate` | {c.reclaim_rate} | tonnes reclaimed per tonne stacked |
| `cut_tonnes` | {c.cut_tonnes:.0f} t | the parcel size the plant receives |
| pad | {c.nx} x {c.ny} cells at {c.cell_m} m | {c.nx * c.cell_m:.0f} by {c.ny * c.cell_m:.0f} metres |

## Operating regimes

{_variant_table(c)}

## Reproduce it

```bash
python data-pipeline/run.py {c.id} --output build/check --band-seeds 5
```

Omit `--output` only for an intentional canonical release bake. Everything about this case is a pure
function of its parameters and the seed, so two runs produce a byte-identical trace.
"""


def cases_readme() -> str:
    by_cat: dict[str, list] = {}
    for c in CASES:
        by_cat.setdefault(c.category, []).append(c)

    out = BANNER + """# Cases and categories

The case registry IS the validation design (ADR-0069 clause 4), not a set of examples. Every case
carries a category, a scientific reason for inclusion, fixed seeds, an expected behaviour, a kill
criterion, and a split assignment.

## The five axes, and why each is separate

* **Stacking geometry** is the primary axis: the build method decides how many layers a cut crosses,
  and that is the dominant term in everything downstream.
* **Reclaim method** is independent of the build. It is held at chevron so the comparison is clean,
  and `G01_chevron` serves as the full-face reference rather than being duplicated as an `R01`.
* **Input variability** is the autocorrelation of the incoming stream, which decides whether the
  layers a cut crosses are independent enough for the bed to help at all.
* **Segregation regime** covers whether kinetic sieving biases the cut, and whether the two species
  have different enough repose angles to stratify.
* **Controls** are three, each with a numerical kill criterion. Without them a plausible wrong answer
  is indistinguishable from a right one.

## Splits

By seed AND input structure. Splitting by seed alone would leak the SHAPE of the stream, so a model
trained on every structure and tested on the same structures learns the four shapes rather than the
physics. All cases below are held out of surrogate training entirely.

## The coverage matrix

| case | category | stacking | reclaim | structure | Sr | passes |
|---|---|---|---|---|---|---|
"""
    for c in CASES:
        out += (f"| [`{c.id}`]({c.id}.md) | {c.category} | {c.stacking} | {c.reclaim} "
                f"| {c.structure} | {c.sr} | {c.n_passes} |\n")

    out += "\n## By category\n\n"
    for cat, label in CATEGORIES.items():
        out += f"### {cat}\n\n{label}.\n\n"
        for c in by_cat.get(cat, []):
            out += f"- [`{c.id}`]({c.id}.md) - {c.expected_band}\n"
        out += "\n"
    return out


def data_contract() -> str:
    out = BANNER + """# The two data contracts

## Contract 1, ingestion: raw to pipeline

The bring-your-own-data gate. A reader with a real dispatch export loads it through the same reader
the product uses internally, and gets a clear answer about what was accepted, what was thrown out, and
what was kept but is suspicious.

### The outlier policy, in words

* A row failing a HARD range is **rejected**, with the reason recorded and counted. Nothing is
  silently coerced: a coerced row looks like data and is not.
* A row failing a SOFT check is **flagged**: accepted, counted, carried into the manifest, and
  rendered with a marker in the app.
* Rows out of time order are rejected, because a stockpile is a sequence and reordering it silently
  would change the answer.
* Dumps outside the declared pad extent are rejected, because a dump with no cell to land in has no
  meaning in this model.

The two soft checks are a grade more than four robust sigmas from the file's own median, using the
median absolute deviation so the outliers being looked for cannot inflate the scale that is supposed
to catch them; and moisture above 20 percent, because the dry angle of repose stops being valid for
wet handling.

### The columns

| column | unit | rule |
|---|---|---|
"""
    for r in contract_doc():
        out += f"| `{r['column']}` | {r['unit']} | {r['rule']} |\n"

    out += """
## Contract 2, artifact: pipeline to web

The manifest is a PURE function of parameters and seed: no wall-clock, no host name, no absolute
path. A manifest that changes on every re-bake makes the git history of the scientific evidence
useless, because a real change stops being distinguishable from a re-run.

The trace carries the EVENTS and the geometry: the dumps, the cuts with their provenance fractions,
a handful of height snapshots and the final field. It does NOT carry the verdicts. The variance
reduction ratio, the variograms, the efficiency against the ideal bound, the residence-time character
and the recommendation are all recomputed in the browser from those events. A trace that shipped a
baked ratio would be a slide, and its number would be unfalsifiable.

`frontend/src/lib/contract.types.ts` mirrors this schema in TypeScript, so a drift between the Python
writer and the browser reader fails `tsc` rather than showing up as an empty panel in production.

## The reclaim geometry table

A reclaim geometry is two numbers: the fraction of the face width the machine engages, and how far
down the column it reaches in one cut. Together they decide how many stacked layers land in the cut.

| method | reach | rule | machine |
|---|---|---|---|
"""
    for k, v in RECLAIM_GEOMETRY.items():
        rule = "proportional across the whole column" if v["proportional"] else "from the top down"
        out += f"| `{k}` | {v['depth'] * 100:.0f} % | {rule} | {v['machine']} |\n"
    return out


def build() -> dict[Path, str]:
    pages: dict[Path, str] = {DOCS / "cases" / "README.md": cases_readme(),
                              DOCS / "data-contract.md": data_contract()}
    for c in CASES:
        pages[DOCS / "cases" / f"{c.id}.md"] = case_page(c)
    return pages


def main() -> None:
    ap = argparse.ArgumentParser(prog="gen_docs")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    pages = build()
    stale = []
    for path, text in pages.items():
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current != text:
            stale.append(path)
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8", newline="\n")
    if args.check:
        if stale:
            print(f"STALE: {len(stale)} generated doc page(s) do not match the code:")
            for p in stale:
                print(f"  {p.relative_to(ROOT)}")
            print("Run: python scripts/gen_docs.py")
            sys.exit(1)
        print(f"OK: {len(pages)} generated doc pages match the code.")
        return
    print(f"wrote {len(stale)} of {len(pages)} generated doc pages")


if __name__ == "__main__":
    main()
