#!/usr/bin/env python3
"""Generate the parts of the docs wiki that are DERIVED from the code, so they cannot drift.

Three things in the wiki are restatements of what the code already declares: the scenario pages, the
scenario index, and the ingestion contract table. Writing them by hand guarantees that the first edit
to a kill criterion or a validation range leaves the documentation quietly wrong, and quietly wrong
documentation is worse than none, because a reader trusts it.

Everything else in `docs/` is authored prose and lives in git, not here.

    python scripts/gen_docs.py
    python scripts/gen_docs.py --check     # exit 1 if any generated page is stale
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "data-pipeline"))

from bedblend.dump import MEASURED_LENGTH_M, MEASURED_THICKNESS_M, MEASURED_WIDTH_M  # noqa: E402
from bedblend.reclaim import ReclaimMethod  # noqa: E402
from pipeline.io.contract import contract_doc  # noqa: E402
from pipeline.scenarios import SCENARIOS  # noqa: E402

DOCS = ROOT / "docs"
BANNER = "<!-- GENERATED by scripts/gen_docs.py. Do not edit; edit the code it reads. -->\n\n"


def scenario_page(s) -> str:
    plan = s.plan()
    a = plan.areas[0]
    pad_w = s.pad_nx * s.cell_m
    pad_h = s.pad_ny * s.cell_m
    classes = ", ".join(s.classes)
    return BANNER + f"""# Scenario `{s.id}`

**{s.title_en}**

{s.summary_en}

## Why it is in the product

{s.reason}

## Kill criterion

> {s.kill_criterion}

This is the statement that turns the scenario from a demonstration into a test. It says, in advance,
what result would mean the code is wrong, and the bake gate fails on it rather than writing a
plausible artifact.

## The site

| parameter | value | what it controls |
|---|---|---|
| pad | {s.pad_nx} x {s.pad_ny} cells at {s.cell_m} m | {pad_w:.0f} by {pad_h:.0f} metres |
| ground | `{s.fill.value}` fill | one of the five published stockpile fill types; only `heaped` is a flat pad |
| relief | {s.relief_m:.0f} m | the vertical range of the landform, which decides whether topography is a detail or the dominant constraint |
| shovel | {s.shovel_xy[0]:.0f}, {s.shovel_xy[1]:.0f} m | the loading point, deliberately OUTSIDE every dump area |

## The plan

| parameter | value | what it controls |
|---|---|---|
| areas | {s.n_areas} ({classes}) | named dump location polygons, which is how a fleet-management system locates a load |
| area size | {s.area_width_m:.0f} x {s.area_length_m:.0f} m | the footprint of each |
| benches | {s.n_benches} at {s.bench_height_m:.0f} m | lifts, built upward the way a pit cuts downward |
| row spacing | {plan.row_spacing_m:.0f} m | separation of the paddock rows that lay the base layer |
| tip spacing | {plan.tip_spacing_m:.0f} m | separation of loads along a row |
| dozer cadence | every {plan.loads_per_dozer_pass} loads | the published practice is to doze after two rows |
| access ramp | {a.ramp_width_m:.0f} m wide | reserved corridor; nothing is tipped on it, so the pile cannot grow over its own way in |

## The material and the stream

| parameter | value | what it controls |
|---|---|---|
| repose angle | {s.repose_deg:.0f} deg dry | not a constant of the ore: it rises with moisture and collapses past saturation |
| loads | {s.n_loads} | the size of the campaign |
| shovel dwell | {s.loads_per_block} loads per dig block | THE control on stream autocorrelation. Consecutive trucks load from the same block, so the correlation length is a consequence of this rather than an input |
| grade | {s.mean_grade:.2f} mean, {s.block_sd:.2f} between blocks | the incoming distribution |
| trucks | {s.n_trucks} | fleet size |

## Reclaim

| parameter | value |
|---|---|
| cut size | {s.cut_tonnes:.0f} t |
| cuts | {s.n_cuts} |
| method | `{ReclaimMethod.FULL_HEIGHT.value}`, a vertical face through every lift |

## Reproduce it

```bash
python data-pipeline/run.py {s.id} --output build/check
```

Omit `--output` only for an intentional canonical bake. Everything about this scenario is a pure
function of its parameters and the seed ({s.seed}), so two runs produce an identical manifest.
"""


def scenarios_readme() -> str:
    out = BANNER + """# Scenarios

The scenario registry IS the validation design, not a set of examples. Every scenario carries a
reason for inclusion, a fixed seed, and a kill criterion that the bake gate enforces.

## What each one is for

"""
    for s in SCENARIOS:
        out += f"### [`{s.id}`]({s.id}.md), {s.title_en}\n\n{s.reason}\n\n"

    out += """## The matrix

| scenario | ground | areas | benches | loads | trucks | tags |
|---|---|---|---|---|---|---|
"""
    for s in SCENARIOS:
        tags = ", ".join(s.tags)
        out += (
            f"| [`{s.id}`]({s.id}.md) | {s.fill.value} | {s.n_areas} | {s.n_benches} "
            f"| {s.n_loads} | {s.n_trucks} | {tags} |\n"
        )

    out += f"""
## What every bake is gated on

These are checked on the ACTUAL artifact, not on a synthetic fixture, because a passing unit test does
not prove the shipped trace is sound.

* **Zero cell pairs standing over the angle of repose.** The predecessor finished a build with 446 of
  them, the worst at 55.9 degrees against an imposed 37, and that is what rendered as spikes.
* **The block ledger agrees with the terrain**, column by column. A disagreement means material was
  placed without being recorded or recorded without being placed, and every grade downstream is wrong.
* **Mass conserved** to one part in a million against the loads actually placed.
* **No cell below its original ground elevation**, which would be excavation nobody performed.

## The measured envelope every dump is compared against

Dump geometry is calibrated against 28 real dumps surveyed by UAV photogrammetry, not assumed.

| quantity | measured range |
|---|---|
| length | {MEASURED_LENGTH_M[0]:.0f} to {MEASURED_LENGTH_M[1]:.0f} m |
| width | {MEASURED_WIDTH_M[0]:.0f} to {MEASURED_WIDTH_M[1]:.0f} m |
| maximum thickness | {MEASURED_THICKNESS_M[0]:.3f} to {MEASURED_THICKNESS_M[1]:.3f} m |

Source: Young, A.; Rogers, W. P. A High-Fidelity Modelling Method for Mine Haul Truck Dumping
Process. *Mining* **2022**, 2(1), 86-102. doi:10.3390/mining2010006, table 5.
"""
    return out


def data_contract() -> str:
    out = BANNER + """# The two data contracts

## Contract 1, ingestion: raw to pipeline

The bring-your-own-data gate. A reader with a real dispatch export loads it through the same reader
the product uses internally, and gets a clear answer about what was accepted, what was thrown out, and
what was kept but is suspicious.

### The outlier policy, in words

* A row failing a HARD range is **rejected**, with the reason recorded and counted. Nothing is
  silently coerced: a coerced row looks like data and is not.
* A row failing a SOFT check is **flagged**: accepted, counted, carried into the manifest, and
  rendered with a marker in the app.
* Rows out of time order are rejected, because a stockpile is a sequence and reordering it silently
  would change the answer.
* Dumps outside the declared pad extent are rejected, because a dump with no cell to land in has no
  meaning in this model.

The two soft checks are a grade more than four robust sigmas from the file's own median, using the
median absolute deviation so the outliers being looked for cannot inflate the scale that is supposed
to catch them; and moisture above 20 percent, because the dry angle of repose stops being valid for
wet handling.

### The columns

| column | unit | rule |
|---|---|---|
"""
    for r in contract_doc():
        out += f"| `{r['column']}` | {r['unit']} | {r['rule']} |\n"

    out += """
Note the last two rows. A real fleet-management dump event locates a load by the **name and bench
height of a dump location polygon**, not by a bare coordinate. That is the operational reason a dump
plan exists and why feeding points are not arbitrary, and the predecessor's schema had no equivalent
field at all.

## Contract 2, artifact: pipeline to web

The manifest is a PURE function of the scenario and its seed: no wall-clock, no host name, no absolute
path. A manifest that changed on every re-bake would make the git history of the scientific evidence
useless, because a real change would stop being distinguishable from a re-run.

The trace carries the EVENTS and the GEOMETRY: the dump plan, every load with its approach and
departure path, the surface, the block field and the reclaim cuts. It does NOT carry the verdicts. The
variance reduction ratio, the variograms, the efficiency against the ideal bound, the sector rollups
and their confidence intervals are all recomputed in the browser from those events. A trace that
shipped a baked ratio would be a slide, and its number would be unfalsifiable.

`frontend/src/lib/scenario.ts` mirrors this schema in TypeScript, so a drift between the Python writer
and the browser reader fails `tsc` rather than showing up as an empty panel in production.

## Why the simulation is baked rather than run live

The engine routes every load over the trafficable surface, floods the pad for reachability, relaxes
after every operation and sorts each cascading load by size. That is tens of seconds per few hundred
loads. Running it in a page would mean either a frozen tab or a model simple enough to be wrong, and
the previous version of this product chose the second.
"""
    return out


def build() -> dict[Path, str]:
    pages: dict[Path, str] = {
        DOCS / "scenarios" / "README.md": scenarios_readme(),
        DOCS / "data-contract.md": data_contract(),
    }
    for s in SCENARIOS:
        pages[DOCS / "scenarios" / f"{s.id}.md"] = scenario_page(s)
    return pages


def main() -> None:
    ap = argparse.ArgumentParser(prog="gen_docs")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    pages = build()
    stale = []
    for path, text in pages.items():
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current != text:
            stale.append(path)
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8", newline="\n")
    if args.check:
        if stale:
            print(f"STALE: {len(stale)} generated doc page(s) do not match the code:")
            for p in stale:
                print(f"  {p.relative_to(ROOT)}")
            print("Run: python scripts/gen_docs.py")
            sys.exit(1)
        print(f"OK: {len(pages)} generated doc pages match the code.")
        return
    print(f"wrote {len(stale)} of {len(pages)} generated doc pages")


if __name__ == "__main__":
    main()
